/**
 * English dictionary.
 *
 * Key set must stay identical to `tr.ts`; the integrity test fails the build
 * when a key exists in one dictionary but not the other. Terminology follows
 * standard winemaking usage (must, lot, blend, racking, vintage).
 */
export const EN: Record<string, string> = {
  // ----------------------------------------------------------------- common
  'app.ad': 'Smart Winery Management System',
  'app.oturumdogrulaniyor': 'Verifying session…',
  'app.kisa': 'Winery',
  'genel.kaydet': 'Save',
  'genel.iptal': 'Cancel',
  'genel.sil': 'Delete',
  'genel.duzenle': 'Edit',
  'genel.yeni': 'New',
  'genel.ara': 'Search…',
  'genel.yukleniyor': 'Loading…',
  'genel.kayityok': 'No records found.',
  'genel.hata': 'Error',
  'genel.kapat': 'Close',
  'genel.onayla': 'Approve',
  'genel.reddet': 'Reject',
  'genel.detay': 'Details',
  'genel.geri': 'Back',
  'genel.toplam': 'Total',
  'genel.vazgec': 'Cancel',
  'genel.tumu': 'All',
  'genel.evet': 'Yes',
  'genel.hayir': 'No',
  'genel.tarih': 'Date',
  'genel.durum': 'Status',
  'genel.kod': 'Code',
  'genel.ad': 'Name',
  'genel.aciklama': 'Description',
  'genel.islem': 'Action',
  'genel.yetkiyok': 'You do not have permission to view this page.',
  'genel.yetkiyok.ipucu':
    'Contact your system administrator for access. This attempt is recorded in the audit log.',
  'genel.sayfabulunamadi': 'Page not found.',
  'genel.sayfabulunamadi.ipucu': 'The address may be wrong; pick a section from the menu.',

  // ------------------------------------------------------------------ login
  'giris.baslik': 'Sign In',
  'giris.kullanici': 'Username or e-mail',
  'giris.parola': 'Password',
  'giris.gonder': 'Sign in',

  // ------------------------------------------------------------------- menu
  'menu.pano': 'Dashboard',
  'menu.bag': 'Vineyard & Intake',
  'menu.parti': 'Lots',
  'menu.tank': 'Tanks',
  'menu.fermantasyon': 'Fermentation',
  'menu.lab': 'Laboratory',
  'menu.recete': 'Recipes & Blending',
  'menu.fici': 'Barrels & Cellar',
  'menu.siseleme': 'Bottling',
  'menu.stok': 'Inventory & Shipping',
  'menu.bakim': 'Maintenance',
  'menu.rapor': 'Reports',
  'menu.istatistik': 'Statistics',
  'menu.yedekleme': 'Backup',
  'menu.ai': 'AI Center',
  'menu.terminal': 'AI Terminal',
  'menu.denetim': 'Audit Log',
  'menu.kullanici': 'Users',
  'menu.ayarlar': 'Settings',
  'menu.egitim': 'Training & Guide',

  // ------------------------------------------------------------ shell/header
  'kabuk.altbaslik': 'Management System',
  'kabuk.menudaralt': 'Collapse/expand menu',
  'kabuk.dil': 'Language',
  'kabuk.tema': 'Toggle theme',
  'kabuk.cikis': 'Sign out',
  'kabuk.uyari': 'Open alerts',
  'kabuk.altbilgi': 'AI output is decision support only.',

  // --------------------------------------------------------------- training
  'egitim.baslik': 'Training & User Guide',
  'egitim.aciklama': 'Role-based, step-by-step modules · each links to the real screen',
  'egitim.sadecerolum': 'My role only',
  'egitim.ekip': 'Team status',
  'egitim.ekipdurumu': 'Team training status',
  'egitim.ekipaciklama': 'Who completed which module · asked in food-safety audits',
  'egitim.kisi': 'Person',
  'egitim.rol': 'Role',
  'egitim.tamamlanan': 'Completed',
  'egitim.denenen': 'Attempted',
  'egitim.genelilerleme': 'Overall progress',
  'egitim.modulyok': 'No training module matches your role.',
  'egitim.modulyok.ipucu': 'Clear the filter to see all modules.',
  'egitim.dakika': 'min',
  'egitim.adim': 'Step',
  'egitim.soru': 'questions',
  'egitim.soruda': 'of',
  'egitim.dogru': 'correct',
  'egitim.tumumoduller': 'All modules',
  'egitim.ekranaGit': 'Open screen',
  'egitim.ileri': 'Next',
  'egitim.sinav': 'Quiz',
  'egitim.sinavaciklama': 'Answer every question; pass mark is 70%',
  'egitim.sinavabasla': 'Start quiz',
  'egitim.sinavibitir': 'Finish quiz',
  'egitim.sonuc': 'Quiz result',
  'egitim.gecti': 'Passed',
  'egitim.kaldi': 'Try again',
  'egitim.dogrucevap': 'Correct answer',
  'egitim.tekrar': 'Retry',
  'egitim.bitir': 'Finish',

  // ------------------------------------------- sayfa çevirileri
  'aiterminal.aciklama': 'Plan → approval → Git checkpoint → run → test → merge/roll back',
  'aiterminal.alan.dosyalar': 'Affected files',
  'aiterminal.alan.dosyalaripucu': 'One relative path per line',
  'aiterminal.alan.istek': 'What would you like done?',
  'aiterminal.alan.istekyertutucu': 'E.g. Add a density chart to the fermentation measurement screen and write its tests.',
  'aiterminal.alan.komutlar': 'Commands to run',
  'aiterminal.alan.komutlaripucu': 'One command per line',
  'aiterminal.alan.llmkullan': 'Request a plan from the language model',
  'aiterminal.baslik': 'AI Terminal / Developer Agent',
  'aiterminal.bos.gorevyok': 'No tasks.',
  'aiterminal.bos.secilmedi': 'No task selected.',
  'aiterminal.bos.secilmediipucu': 'Select a task on the left or create a new plan. No command is ever run without your approval.',
  'aiterminal.calisma.cikis': 'exit',
  'aiterminal.calisma.engellendi': 'blocked',
  'aiterminal.calisma.zamanasimi': 'timed out',
  'aiterminal.denetle.engellendi': 'BLOCKED',
  'aiterminal.denetle.yertutucu': 'Check a command without running it: python -m pytest -q',
  'aiterminal.dogrulama.basarisiz': 'Tests failed',
  'aiterminal.dogrulama.gecti': 'Tests passed',
  'aiterminal.dugme.calistir': '3. Run commands',
  'aiterminal.dugme.denetle': 'Check',
  'aiterminal.dugme.dogrula': '4. Run lint + tests',
  'aiterminal.dugme.gerial': 'Roll back',
  'aiterminal.dugme.onayla': '2. Approve (create checkpoint)',
  'aiterminal.dugme.planolustur': 'Create plan',
  'aiterminal.gorev.dal': 'branch',
  'aiterminal.gorev.engellendi': 'This plan was blocked by the security policy.',
  'aiterminal.gorev.komutdenetimi': 'Command check',
  'aiterminal.gorev.kontrolnoktasi': 'Checkpoint:',
  'aiterminal.gorev.planadimlari': 'Plan steps',
  'aiterminal.guvenlik.calismaalani': 'Workspace',
  'aiterminal.guvenlik.degisiklikvar': 'uncommitted changes',
  'aiterminal.guvenlik.depodegil': 'Not a repository',
  'aiterminal.guvenlik.engellenenislemler': 'and blocked operations',
  'aiterminal.guvenlik.engelli': 'Blocked',
  'aiterminal.guvenlik.evet': 'Yes',
  'aiterminal.guvenlik.hayir': 'No',
  'aiterminal.guvenlik.izinli': 'Allowed',
  'aiterminal.guvenlik.izinliaraclar': 'Allowed tools',
  'aiterminal.guvenlik.onayzorunlu': 'Approval required',
  'aiterminal.guvenlik.saniye': 's',
  'aiterminal.guvenlik.sinir': 'Timeout / output limit',
  'aiterminal.kart.ciktilar': 'Command output',
  'aiterminal.kart.diff': 'Change diff',
  'aiterminal.kart.dogrulama': 'Verification results',
  'aiterminal.kart.gecmis': 'Task history',
  'aiterminal.kart.guvenlik': 'Security boundaries',
  'aiterminal.kart.guvenlikaciklama': 'These constraints are enforced at code level and cannot be changed by AI',
  'aiterminal.kart.plan': 'Step 1 — Create plan',
  'aiterminal.uyari.gerial': 'Changes will be rolled back to the checkpoint. Do you confirm?',
  'aiterminal.uyari.redgerekce': 'Reason for rejection:',
  'asama.dinlendirme': 'Aging',
  'asama.fermantasyon': 'Fermentation',
  'asama.kupaj': 'Blending',
  'asama.malolaktik': 'Malolactic',
  'asama.olgunlastirma': 'Maturation',
  'asama.sira': 'Must',
  'asama.siseleme': 'Bottling',
  'asama.stabilizasyon': 'Stabilization',
  'asama.tamamlandi': 'Completed',
  'asama.uzum_kabul': 'Grape intake',
  'ayarlar.aciklama': 'Interface preferences and AI provider configuration',
  'ayarlar.alan.cikismaliyet': 'Output cost (1K tokens)',
  'ayarlar.alan.dil': 'Language',
  'ayarlar.alan.dilipucu': 'The infrastructure is multilingual; new languages are supported by adding a dictionary.',
  'ayarlar.alan.girismaliyet': 'Input cost (1K tokens)',
  'ayarlar.alan.modelyertutucu': 'Fetch the model list first',
  'ayarlar.alan.seciniz': 'Select…',
  'ayarlar.alan.sunucu': 'Server address',
  'ayarlar.alan.tema': 'Theme',
  'ayarlar.alan.varsayilanmodel': 'Default model',
  'ayarlar.alan.yenidendeneme': 'Retries',
  'ayarlar.alan.zamanasimi': 'Timeout (s)',
  'ayarlar.anahtar.parmakizi': 'fingerprint',
  'ayarlar.anahtar.tanimli': 'Key configured',
  'ayarlar.anahtar.tanimsiz': 'No API key configured — this provider cannot be used.',
  'ayarlar.baslik': 'Settings',
  'ayarlar.bilgi.anahtaroncesi': 'API keys are stored',
  'ayarlar.bilgi.anahtarsonrasi': '(Fernet/AES) and are never shown in clear text on any screen, in logs, or in API responses. They are write-only; they cannot be read back. You can verify a key by its fingerprint.',
  'ayarlar.bilgi.anahtarvurgu': 'encrypted',
  'ayarlar.dugme.baglantitest': 'Test connection',
  'ayarlar.dugme.degistir': 'Change',
  'ayarlar.dugme.ekle': 'Add',
  'ayarlar.dugme.modelyenile': 'Refresh model list',
  'ayarlar.dugme.sifrelikaydet': 'Encrypt and save',
  'ayarlar.dugme.sohbetlitest': 'Test with chat',
  'ayarlar.gizlilik.harici': 'External cloud',
  'ayarlar.gizlilik.yerel': 'Local · no data leaves',
  'ayarlar.kart.arayuz': 'Interface',
  'ayarlar.kip.anahtar': 'API key',
  'ayarlar.kip.bilgioncesi': 'The key is sent from the browser to the server and stored',
  'ayarlar.kip.bilgisonrasi': 'in the database. It is never displayed anywhere outside this screen. Do not share the key by e-mail, chat or screenshot.',
  'ayarlar.mesaj.anahtarsilindi': 'API key deleted.',
  'ayarlar.mesaj.kaydedildi': 'Setting saved.',
  'ayarlar.mesaj.modelbulundu': 'models found.',
  'ayarlar.mesaj.modelhata': 'Model list could not be retrieved',
  'ayarlar.mesaj.yanit': 'Response',
  'ayarlar.saglayici.durum': 'Status:',
  'ayarlar.saglayici.etkin': 'Enabled',
  'ayarlar.saglayici.modellistesi': 'model list',
  'ayarlar.tema.acik': 'Light',
  'ayarlar.tema.koyu': 'Dark',
  'ayarlar.tema.sistem': 'Follow system preference',
  'ayarlar.uyari.anahtarsil': 'Delete the API key?',
  'ayarlar.uyari.buluttest': 'This test sends a small request to the cloud provider and may incur a small charge. Continue?',
  'ayarlar.uyari.yereltest': 'A small test request will be sent. Continue?',
  'bag.aciklama': 'Vineyard/parcel definitions, grape varieties and weighbridge intake records',
  'bag.arama.kabul': 'Search code or plate…',
  'bag.baslik': 'Vineyard & Grape Intake',
  'bag.bos.bag': 'No vineyard records.',
  'bag.bos.cesit': 'No grape variety defined.',
  'bag.bos.kabul': 'No grape intake records.',
  'bag.bos.kabulipucu': 'Enter the first intake record when harvest begins.',
  'bag.bos.parsel': 'No parcel records.',
  'bag.dugme.kabul': 'Grape intake',
  'bag.form.asitlik': 'Total acidity (g/L)',
  'bag.form.bag': 'Vineyard',
  'bag.form.birimfiyat': 'Unit price (TRY/kg)',
  'bag.form.brix': 'Brix (°Bx)',
  'bag.form.cesit': 'Grape variety',
  'bag.form.hasattarihi': 'Harvest date',
  'bag.form.kalite': 'Quality grade',
  'bag.form.netagirlik': 'Net weight (kg)',
  'bag.form.notlar': 'Notes',
  'bag.form.parsel': 'Parcel',
  'bag.form.ph': 'pH',
  'bag.form.plaka': 'Vehicle plate',
  'bag.form.plakaornek': '35 ABC 123',
  'bag.form.seciniz': 'Select…',
  'bag.form.sicaklik': 'Temperature (°C)',
  'bag.kalite.a': 'A — First grade',
  'bag.kalite.b': 'B — Second grade',
  'bag.kalite.c': 'C — Third grade',
  'bag.kalite.red': 'Rejected',
  'bag.kip.baslik': 'New grape intake',
  'bag.sekme.bag': 'Vineyards',
  'bag.sekme.cesit': 'Grape Varieties',
  'bag.sekme.kabul': 'Grape Intake',
  'bag.sekme.parsel': 'Parcels',
  'bag.tablo.alan': 'Area (da)',
  'bag.tablo.bag': 'Vineyard',
  'bag.tablo.bagadi': 'Vineyard name',
  'bag.tablo.bolge': 'Region',
  'bag.tablo.brix': 'Brix',
  'bag.tablo.cesit': 'Variety',
  'bag.tablo.dikim': 'Planted',
  'bag.tablo.hasat': 'Harvest',
  'bag.tablo.hedefbrix': 'Target Brix',
  'bag.tablo.hedefph': 'Target pH',
  'bag.tablo.kalite': 'Grade',
  'bag.tablo.kod': 'Code',
  'bag.tablo.koy': 'Village/Locality',
  'bag.tablo.mense': 'Origin',
  'bag.tablo.netkg': 'Net kg',
  'bag.tablo.omca': 'Vines',
  'bag.tablo.parsel': 'Parcels',
  'bag.tablo.parselad': 'Parcel',
  'bag.tablo.ph': 'pH',
  'bag.tablo.qr': 'QR',
  'bag.tablo.qrac': 'Open QR code',
  'bag.tablo.rakim': 'Altitude (m)',
  'bag.tablo.renk': 'Colour',
  'bag.tablo.toprak': 'Soil',
  'bag.tablo.tutar': 'Amount',
  'bakim.aciklama': 'Equipment maintenance, breakdown records and CIP/cleaning verification',
  'bakim.baslik': 'Maintenance & Cleaning',
  'bakim.birim.gun': 'days',
  'bakim.dugme.yenikayit': 'Maintenance record',
  'bakim.ekipman.ad': 'Equipment',
  'bakim.ekipman.bos': 'No equipment records.',
  'bakim.ekipman.durum': 'Status',
  'bakim.ekipman.kalan': 'Remaining',
  'bakim.ekipman.kod': 'Code',
  'bakim.ekipman.sonbakim': 'Last maintenance',
  'bakim.ekipman.sonrakibakim': 'Next maintenance',
  'bakim.ekipman.tur': 'Type',
  'bakim.ekipman.uretici': 'Manufacturer',
  'bakim.form.aciklama': 'Description',
  'bakim.form.baslik': 'Title',
  'bakim.form.cipbaslik': 'CIP details',
  'bakim.form.dogrulandi': 'Cleaning verified (will be treated as sanitized)',
  'bakim.form.durus': 'Downtime (min)',
  'bakim.form.ekipman': 'Equipment',
  'bakim.form.kimyasal': 'Chemical',
  'bakim.form.kimyasalornek': 'Caustic 2%',
  'bakim.form.maliyet': 'Cost (TRY)',
  'bakim.form.sicaklik': 'Temperature (°C)',
  'bakim.form.sure': 'Duration (min)',
  'bakim.form.tamamlandi': 'Work completed (an unfinished breakdown record sets the equipment to "faulty")',
  'bakim.form.tank': 'Tank',
  'bakim.form.tankipucu': 'Either equipment or a tank must be selected',
  'bakim.form.tur': 'Record type',
  'bakim.kayit.baslangic': 'Start',
  'bakim.kayit.baslik': 'Title',
  'bakim.kayit.bitis': 'End',
  'bakim.kayit.bos': 'No maintenance records.',
  'bakim.kayit.durus': 'Downtime (min)',
  'bakim.kayit.ekipman': 'Equipment',
  'bakim.kayit.kod': 'Code',
  'bakim.kayit.maliyet': 'Cost',
  'bakim.kayit.sorumlu': 'Responsible',
  'bakim.kayit.tur': 'Type',
  'bakim.kip.baslik': 'Maintenance / cleaning record',
  'bakim.sekme.ekipman': 'Equipment',
  'bakim.sekme.kayit': 'Maintenance Records',
  'bakim.tur.ariza': 'Breakdown',
  'bakim.tur.cip': 'CIP (clean-in-place)',
  'bakim.tur.kalibrasyon': 'Calibration',
  'bakim.tur.periyodik': 'Preventive maintenance',
  'bakim.tur.temizlik': 'Cleaning',
  'bakim.yaklasan.baslik': 'Upcoming and overdue maintenance',
  'bakim.yaklasan.durum': 'Status',
  'bakim.yaklasan.ekipman': 'Equipment',
  'bakim.yaklasan.gecikmis': 'overdue',
  'bakim.yaklasan.gungecikti': 'days overdue',
  'bakim.yaklasan.kalangun': 'Days left',
  'bakim.yaklasan.planlanantarih': 'Scheduled date',
  'bakim.yaklasan.tur': 'Type',
  'bakim.yaklasan.yaklasan': 'upcoming',
  'denetim.aciklama': 'Who changed what and when · records cannot be modified or deleted',
  'denetim.baslik': 'Audit Log',
  'denetim.bos.metin': 'No audit records.',
  'denetim.deger.sistem': 'system',
  'denetim.degismezlik.oncesi': 'There is no update or delete endpoint for audit records; a delete attempt is rejected with',
  'denetim.degismezlik.sonrasi': '— secrets such as passwords, API keys and tokens are automatically masked before being recorded.',
  'denetim.detay.degisenalanlar': 'Changed fields',
  'denetim.detay.ip': 'IP address',
  'denetim.detay.istek': 'Request',
  'denetim.detay.kayit': 'Record',
  'denetim.detay.oncekideger': 'Previous value',
  'denetim.detay.sonrakideger': 'New value',
  'denetim.filtre.tumeylemler': 'All actions',
  'denetim.filtre.tumseviyeler': 'All levels',
  'denetim.kart.degismezlik': 'Immutability principle',
  'denetim.kip.baslik': 'Audit record',
  'denetim.seviye.bilgi': 'Info',
  'denetim.seviye.kritik': 'Critical',
  'denetim.seviye.uyari': 'Warning',
  'denetim.tablo.ai': 'AI',
  'denetim.tablo.eylem': 'Action',
  'denetim.tablo.kayitturu': 'Record type',
  'denetim.tablo.kod': 'Code',
  'denetim.tablo.kullanici': 'User',
  'denetim.tablo.ozet': 'Summary',
  'denetim.tablo.seviye': 'Level',
  'denetim.tablo.zaman': 'Time',
  'durum.acik': 'Open',
  'durum.agir': 'Heavy',
  'durum.ahsap': 'Wood',
  'durum.ai_istek': 'AI request',
  'durum.ai_oneri': 'AI suggestion',
  'durum.aktif': 'Active',
  'durum.alkol': 'Alcoholic',
  'durum.ambalaj': 'Packaging',
  'durum.amerikan': 'American',
  'durum.amfora': 'Amphora',
  'durum.ariza': 'Breakdown',
  'durum.arizali': 'Faulty',
  'durum.arsiv': 'Archive',
  'durum.ayar_degisikligi': 'Settings change',
  'durum.bakimda': 'Under maintenance',
  'durum.basarili': 'Succeeded',
  'durum.basarisiz': 'Failed',
  'durum.beklemede': 'Pending',
  'durum.bekliyor': 'Waiting',
  'durum.beton': 'Concrete',
  'durum.bitmis_urun': 'Finished goods',
  'durum.bos': 'Empty',
  'durum.calisiyor': 'Running',
  'durum.calisiyor_gorev': 'Running',
  'durum.cikis': 'Sign out',
  'durum.cip': 'CIP',
  'durum.cozuldu': 'Resolved',
  'durum.devam_ediyor': 'In progress',
  'durum.devre_disi': 'Disabled',
  'durum.diger': 'Other',
  'durum.disa_aktar': 'Export',
  'durum.dolu': 'Full',
  'durum.durakladi': 'Paused',
  'durum.emekli': 'Retired',
  'durum.fiberglas': 'Fiberglass',
  'durum.filtre': 'Filter',
  'durum.fire': 'Loss',
  'durum.fransiz': 'French',
  'durum.geri_alindi': 'Rolled back',
  'durum.giris': 'Sign in',
  'durum.giris_basarisiz': 'Failed sign-in',
  'durum.guncelle': 'Update',
  'durum.hafif': 'Light',
  'durum.hammadde': 'Raw material',
  'durum.hazirlaniyor': 'Preparing',
  'durum.hazirlik': 'Preparation',
  'durum.iade': 'Return',
  'durum.ikincil': 'Secondary',
  'durum.iptal': 'Cancelled',
  'durum.izinsiz_erisim': 'Unauthorized access',
  'durum.kafkas': 'Caucasian',
  'durum.kalibrasyon': 'Calibration',
  'durum.kapandi': 'Closed',
  'durum.karantina': 'Quarantine',
  'durum.katki': 'Additive',
  'durum.kismen_dolu': 'Partially full',
  'durum.kismen_teslim': 'Partially received',
  'durum.kontrol': 'Control',
  'durum.macar': 'Hungarian',
  'durum.okundu': 'Read',
  'durum.olustur': 'Create',
  'durum.onarimda': 'Under repair',
  'durum.onay': 'Approval',
  'durum.onay_bekliyor': 'Awaiting approval',
  'durum.onaylandi': 'Approved',
  'durum.orta_plus': 'Medium+',
  'durum.paslanmaz_celik': 'Stainless steel',
  'durum.periyodik': 'Periodic',
  'durum.plan_hazir': 'Plan ready',
  'durum.planlandi': 'Planned',
  'durum.pompa': 'Pump',
  'durum.pres': 'Press',
  'durum.red': 'Rejection',
  'durum.reddedildi': 'Rejected',
  'durum.rutin': 'Routine',
  'durum.sap_ayirici': 'Destemmer',
  'durum.sarf': 'Consumable',
  'durum.sayim': 'Stock count',
  'durum.senaryo': 'Scenario',
  'durum.sevk_edildi': 'Shipped',
  'durum.sil': 'Delete',
  'durum.siparis_verildi': 'Ordered',
  'durum.siseleme_hatti': 'Bottling line',
  'durum.slavonya': 'Slavonian',
  'durum.sogutma': 'Cooling',
  'durum.tank': 'Tank',
  'durum.taslak': 'Draft',
  'durum.temizlik': 'Cleaning',
  'durum.temizlikte': 'In cleaning',
  'durum.terminal_geri_al': 'Terminal rollback',
  'durum.terminal_komut': 'Terminal command',
  'durum.terminal_onay': 'Terminal approval',
  'durum.terminal_red': 'Terminal rejection',
  'durum.teslim_alindi': 'Received',
  'durum.teslim_edildi': 'Delivered',
  'durum.test_ediliyor': 'Testing',
  'durum.transfer': 'Transfer',
  'durum.uretim_giris': 'Production intake',
  'durum.uretim_tuketim': 'Production consumption',
  'durum.uygulandi': 'Applied',
  'durum.yedek_parca': 'Spare part',
  'durum.yoksayildi': 'Ignored',
  'fermantasyon.aciklama': 'Daily readings, curves, threshold alerts and predicted completion',
  'fermantasyon.alan.baslangicbrix': 'Initial Brix',
  'fermantasyon.alan.brix': 'Brix (°Bx)',
  'fermantasyon.alan.hacim': 'Volume (L)',
  'fermantasyon.alan.hedefbrix': 'Target Brix',
  'fermantasyon.alan.hedefbrixipucu': 'Typically between -1 and 0 for dry wines',
  'fermantasyon.alan.makssicaklik': 'Max. temperature (°C)',
  'fermantasyon.alan.mayasusu': 'Yeast strain',
  'fermantasyon.alan.minsicaklik': 'Min. temperature (°C)',
  'fermantasyon.alan.not': 'Note',
  'fermantasyon.alan.parti': 'Lot',
  'fermantasyon.alan.ph': 'pH',
  'fermantasyon.alan.sapkayonetimi': 'Cap management',
  'fermantasyon.alan.serbestso2': 'Free SO₂ (mg/L)',
  'fermantasyon.alan.sicaklik': 'Temperature (°C)',
  'fermantasyon.alan.tank': 'Tank',
  'fermantasyon.alan.ucucuasitlik': 'Volatile acidity (g/L)',
  'fermantasyon.alan.yogunluk': 'Density',
  'fermantasyon.baslik': 'Fermentation',
  'fermantasyon.bos.kayit': 'No fermentation records.',
  'fermantasyon.bos.olcum': 'No readings recorded yet.',
  'fermantasyon.bos.olcumipucu': 'Enter the first reading to start the curve.',
  'fermantasyon.dugme.basla': 'Start',
  'fermantasyon.dugme.baslat': 'Start fermentation',
  'fermantasyon.dugme.olcumgir': 'Enter reading',
  'fermantasyon.dugme.olcumkaydet': 'Save reading',
  'fermantasyon.durum.devamediyor': 'In progress',
  'fermantasyon.durum.durakladi': 'Paused',
  'fermantasyon.durum.planlandi': 'Planned',
  'fermantasyon.durum.tamamlandi': 'Completed',
  'fermantasyon.filtre.durum': 'Filter by status',
  'fermantasyon.filtre.tumu': 'All statuses',
  'fermantasyon.grafik.anomali': 'readings flagged as anomalies.',
  'fermantasyon.grafik.brix': 'Brix',
  'fermantasyon.grafik.hedefbrix': 'Target Brix',
  'fermantasyon.grafik.ph': 'pH',
  'fermantasyon.grafik.sicaklik': 'Temperature (°C)',
  'fermantasyon.kart.egri': 'fermentation curve',
  'fermantasyon.kart.maya': 'yeast',
  'fermantasyon.kip.baslat': 'Start fermentation',
  'fermantasyon.kip.olcum': 'Enter reading',
  'fermantasyon.olcum.ipucu': 'At least one reading value is required. Target temperature range:',
  'fermantasyon.secim.seciniz': 'Select…',
  'fermantasyon.tablo.anomali': 'Anomaly',
  'fermantasyon.tablo.baslangic': 'Start',
  'fermantasyon.tablo.brix': 'Brix',
  'fermantasyon.tablo.durum': 'Status',
  'fermantasyon.tablo.ilerleme': 'Progress',
  'fermantasyon.tablo.kod': 'Code',
  'fermantasyon.tablo.parti': 'Lot',
  'fermantasyon.tablo.sicaklik': 'Temperature',
  'fermantasyon.tablo.tank': 'Tank',
  'fermantasyon.tablo.tur': 'Type',
  'fermantasyon.tahmin.baslik': 'Predicted completion',
  'fermantasyon.tahmin.not': 'This prediction is derived from the linear slope of the most recent readings and is intended for decision support only.',
  'fici.alan.fire': 'Loss (L)',
  'fici.alan.hacim': 'Volume (L)',
  'fici.alan.islemturu': 'Movement type',
  'fici.alan.not': 'Note',
  'fici.alan.parti': 'Lot',
  'fici.baslik': 'Barrels and Cellar',
  'fici.birim.gun': 'days',
  'fici.birim.yil': 'years',
  'fici.bos.kayit': 'No barrel records.',
  'fici.gorunum.harita': 'Cellar map',
  'fici.gorunum.liste': 'List',
  'fici.hareket.aktarma': 'Transfer',
  'fici.hareket.bosaltim': 'Racking',
  'fici.hareket.dolum': 'Fill',
  'fici.hareket.durum': 'status',
  'fici.hareket.mevcut': 'Current',
  'fici.hareket.onarim': 'Repair',
  'fici.hareket.temizlik': 'Cleaning',
  'fici.hareket.topping': 'Topping up',
  'fici.kart.fici': 'barrels',
  'fici.kip.hareket': 'Barrel movement',
  'fici.ozet.dolu': 'barrels filled',
  'fici.ozet.toplamfire': 'total loss',
  'fici.secim.seciniz': 'Select…',
  'fici.tablo.dolu': 'Filled',
  'fici.tablo.durum': 'Status',
  'fici.tablo.fire': 'Loss (L)',
  'fici.tablo.kapasite': 'Capacity',
  'fici.tablo.kavurma': 'Toast',
  'fici.tablo.kod': 'Code',
  'fici.tablo.mese': 'Oak',
  'fici.tablo.olgunlasma': 'Aging',
  'fici.tablo.parti': 'Lot',
  'fici.tablo.qr': 'QR',
  'fici.tablo.uretici': 'Cooper',
  'fici.tablo.yas': 'Age',
  'giris.hata': 'Sign-in failed.',
  'giris.slogan': 'Every production step from vineyard to bottle in a single panel',
  'giris.yardim': 'If you do not have an account, contact your system administrator.',
  'giris.ilkkurulum':
    'First run: the administrator password is generated during setup and written '
    + 'once to ILK-GIRIS.txt in the data folder. It must be changed at first sign-in, '
    + 'and until then this account can only be used from this computer.',
  // ------------------------------------------------- forced password change
  'parola.zorunlu.baslik': 'You must change your password',
  'parola.zorunlu.aciklama':
    'This account was opened with a temporary password. Until you set a new one, '
    + 'the dashboard, production data, financial records, AI settings, export and '
    + 'backup screens stay closed.',
  'parola.mevcut': 'Current password',
  'parola.yeni': 'New password',
  'parola.tekrar': 'New password (repeat)',
  'parola.kural':
    'At least 10 characters, including one uppercase letter, one lowercase letter '
    + 'and one digit.',
  'parola.eslesmiyor': 'The new passwords do not match.',
  'parola.hata': 'The password could not be changed. Please check the details.',
  'parola.gonder': 'Change password',
  'goreli.dk': 'min ago',
  'goreli.gun': 'd ago',
  'goreli.sa': 'h ago',
  'goreli.simdi': 'just now',
  'istatistikler.aciklama': 'Efficiency, losses and quality consistency · period comparison',
  'istatistikler.bakim.bos': 'No maintenance records.',
  'istatistikler.bakim.cipdogrulama': 'CIP verification',
  'istatistikler.bakim.cipipucu': 'Food safety audit',
  'istatistikler.bakim.cipkaydi': 'CIP records',
  'istatistikler.bakim.durus': 'Downtime (min)',
  'istatistikler.bakim.durusaciklama': 'Total downtime by maintenance type',
  'istatistikler.bakim.durusbaslik': 'Downtime sources',
  'istatistikler.bakim.ekipman': 'Equipment',
  'istatistikler.bakim.ekipmanbaslik': 'Equipment with most downtime',
  'istatistikler.bakim.ekipmanbos': 'No equipment maintenance records.',
  'istatistikler.bakim.gecikenbakim': 'Overdue maintenance',
  'istatistikler.bakim.gecikenipucu': 'Equipment past its scheduled date',
  'istatistikler.bakim.kayit': 'Records',
  'istatistikler.baslik': 'Statistics',
  'istatistikler.birim.adet': 'Count',
  'istatistikler.birim.dakika': 'minutes',
  'istatistikler.birim.gun': 'days',
  'istatistikler.birim.sise': 'bottles',
  'istatistikler.bos.yetki': 'There are no statistics available to you.',
  'istatistikler.fermantasyon.bos': 'No fermentation records.',
  'istatistikler.fermantasyon.durumbaslik': 'Status distribution',
  'istatistikler.fermantasyon.gunlukbrix': 'Daily Brix drop',
  'istatistikler.fermantasyon.ortalamasure': 'Average duration',
  'istatistikler.fermantasyon.surearaligi': 'Duration range',
  'istatistikler.fermantasyon.tamamlanan': 'Completed',
  'istatistikler.fici.bos': 'No barrel records.',
  'istatistikler.fici.buharlasma': 'Evaporation loss',
  'istatistikler.fici.buharlasmaipucu': 'Angel\'s share',
  'istatistikler.fici.doluluk': 'Fill rate',
  'istatistikler.fici.kapasite': 'Capacity',
  'istatistikler.fici.kullanimaciklama': 'Which fill — an indicator of quality and cost',
  'istatistikler.fici.kullanimbaslik': 'Fill count',
  'istatistikler.fici.kullanimbos': 'No usage data.',
  'istatistikler.fici.sayisi': 'Barrel count',
  'istatistikler.fici.yas': 'yrs',
  'istatistikler.fici.yasbaslik': 'Distribution by production year',
  'istatistikler.filtre.rekolteyili': 'Vintage year',
  'istatistikler.filtre.tumyillar': 'All years',
  'istatistikler.fire.firesise': 'reject bottles',
  'istatistikler.fire.huniaciklama': 'Volume flow across stages',
  'istatistikler.fire.hunibaslik': 'From grape to bottle',
  'istatistikler.fire.kayipaciklama': 'The stage where most money is lost',
  'istatistikler.fire.kayipbaslik': 'Where do losses occur?',
  'istatistikler.fire.sira': 'Must',
  'istatistikler.fire.siraverimi': 'Must yield',
  'istatistikler.fire.siraverimiipucu': 'Industry range: 0.65–0.75',
  'istatistikler.fire.toplamkayip': 'Total loss',
  'istatistikler.fire.uzum': 'Grapes',
  'istatistikler.hasat.alan': 'Area (da)',
  'istatistikler.hasat.bag': 'Vineyard',
  'istatistikler.hasat.bos': 'No harvest records.',
  'istatistikler.hasat.cesit': 'Variety',
  'istatistikler.hasat.cesitaciklama': 'Average Brix compared with the target range',
  'istatistikler.hasat.cesitbaslik': 'Ripeness by variety',
  'istatistikler.hasat.cesitbos': 'No variety data.',
  'istatistikler.hasat.curuk': 'Rot %',
  'istatistikler.hasat.durum': 'Status',
  'istatistikler.hasat.hedef': 'Target',
  'istatistikler.hasat.hedefdisi': 'Off target',
  'istatistikler.hasat.hedefte': 'On target',
  'istatistikler.hasat.kalitebaslik': 'Quality grade distribution',
  'istatistikler.hasat.kalitebos': 'No quality data.',
  'istatistikler.hasat.kgasma': 'kg / vine',
  'istatistikler.hasat.kgdekar': 'kg / decare',
  'istatistikler.hasat.ortbrix': 'Avg. Brix',
  'istatistikler.hasat.parsel': 'Parcel',
  'istatistikler.hasat.parselaciklama': 'Raw kilograms mislead; yield per decare is the comparable measure',
  'istatistikler.hasat.parselbaslik': 'Parcel yield',
  'istatistikler.hasat.parselbos': 'No parcel-level harvest records.',
  'istatistikler.hasat.parselbosipucu': 'A parcel may not have been selected during grape intake.',
  'istatistikler.hasat.uzumkg': 'Grapes (kg)',
  'istatistikler.hasat.yilaciklama': 'Total grapes and average Brix',
  'istatistikler.hasat.yilbaslik': 'Vintage year comparison',
  'istatistikler.laboratuvar.analiz': 'Analyses',
  'istatistikler.laboratuvar.analizbirim': 'analyses',
  'istatistikler.laboratuvar.analizsayisi': 'Analysis count',
  'istatistikler.laboratuvar.aylikbaslik': 'Monthly out-of-spec rate',
  'istatistikler.laboratuvar.bos': 'No analyses in the period.',
  'istatistikler.laboratuvar.enaz': 'Min',
  'istatistikler.laboratuvar.encok': 'Max',
  'istatistikler.laboratuvar.olcum': 'Measurements',
  'istatistikler.laboratuvar.ortalama': 'Average',
  'istatistikler.laboratuvar.ortonaysuresi': 'Average approval time',
  'istatistikler.laboratuvar.parametre': 'Parameter',
  'istatistikler.laboratuvar.parametrebaslik': 'Parameter summaries',
  'istatistikler.laboratuvar.parametrebos': 'No parameter measurements.',
  'istatistikler.laboratuvar.specdisi': 'Out of spec',
  'istatistikler.laboratuvar.specdisiyuzde': 'Out of spec %',
  'istatistikler.sekme.bakim': 'Maintenance',
  'istatistikler.sekme.fermantasyon': 'Fermentation',
  'istatistikler.sekme.fici': 'Barrels',
  'istatistikler.sekme.fire': 'Loss Chain',
  'istatistikler.sekme.hasat': 'Vineyard & Harvest',
  'istatistikler.sekme.laboratuvar': 'Laboratory',
  'istatistikler.sekme.siseleme': 'Bottling',
  'istatistikler.sekme.stok': 'Inventory',
  'istatistikler.siseleme.ambalajbaslik': 'Packaging breakdown',
  'istatistikler.siseleme.ambalajbos': 'No packaging data.',
  'istatistikler.siseleme.aylikbaslik': 'Monthly output',
  'istatistikler.siseleme.bos': 'No completed bottling orders.',
  'istatistikler.siseleme.fire': 'Loss',
  'istatistikler.siseleme.fireorani': 'Loss rate',
  'istatistikler.siseleme.hat': 'Line',
  'istatistikler.siseleme.hatbaslik': 'Line comparison',
  'istatistikler.siseleme.hatbos': 'No line data.',
  'istatistikler.siseleme.planlanan': 'Planned',
  'istatistikler.siseleme.sise': 'Bottles',
  'istatistikler.siseleme.uretilen': 'Produced',
  'istatistikler.siseleme.uretilensise': 'Bottles produced',
  'istatistikler.siseleme.verim': 'Yield',
  'istatistikler.stok.aktifkalem': 'Active items',
  'istatistikler.stok.bos': 'No stock movements in the period.',
  'istatistikler.stok.donem': 'Period',
  'istatistikler.stok.donemcikisi': 'Period issues',
  'istatistikler.stok.encokbaslik': 'Most consumed items',
  'istatistikler.stok.gunlukort': 'Daily avg.',
  'istatistikler.stok.hareketsizaciklama': 'Items with no issues during the period — tied-up capital',
  'istatistikler.stok.hareketsizbaslik': 'Dormant stock',
  'istatistikler.stok.hareketsizipucu': 'No issues during the period',
  'istatistikler.stok.hareketsizkalem': 'Dormant items',
  'istatistikler.stok.hic': 'Never',
  'istatistikler.stok.kalem': 'Item',
  'istatistikler.stok.kategori': 'Category',
  'istatistikler.stok.sonhareket': 'Last movement',
  'istatistikler.yukleniyor': 'Calculating statistics…',
  'kullanicilar.aciklama': 'Role-based authorisation · each role sees only the screens it is entitled to',
  'kullanicilar.baslik': 'Users and Roles',
  'kullanicilar.bos.metin': 'No users.',
  'kullanicilar.dugme.aktiflestir': 'Activate',
  'kullanicilar.dugme.ekle': 'Add user',
  'kullanicilar.dugme.olustur': 'Create',
  'kullanicilar.dugme.parolasifirla': 'Reset password',
  'kullanicilar.dugme.pasifeal': 'Deactivate',
  'kullanicilar.dugme.sifirla': 'Reset',
  'kullanicilar.durum.aktif': 'Active',
  'kullanicilar.durum.pasif': 'Inactive',
  'kullanicilar.form.geciciparola': 'Temporary password',
  'kullanicilar.form.parolaipucu': 'At least 10 characters; must contain an upper-case letter, a lower-case letter and a digit. The user changes it at first sign-in.',
  'kullanicilar.form.rolipucu': 'You can select more than one role (hold Ctrl)',
  'kullanicilar.form.yenigeciciparola': 'New temporary password',
  'kullanicilar.kart.rolaciklama': 'Click a role to see the permissions it holds',
  'kullanicilar.kart.rolkatalog': 'Role and permission catalogue',
  'kullanicilar.parola.bilgi': 'When the password is reset, all sessions belonging to the user are closed and a password change is required at first sign-in. The operation is written to the audit log.',
  'kullanicilar.rol.yetkisayisi': 'permissions',
  'kullanicilar.tablo.adsoyad': 'Full name',
  'kullanicilar.tablo.departman': 'Department',
  'kullanicilar.tablo.durum': 'Status',
  'kullanicilar.tablo.eposta': 'E-mail',
  'kullanicilar.tablo.islem': 'Actions',
  'kullanicilar.tablo.kullaniciadi': 'Username',
  'kullanicilar.tablo.roller': 'Roles',
  'kullanicilar.tablo.songiris': 'Last sign-in',
  'laboratuvar.aciklama': 'Sample management, analysis results, specifications and approval workflow',
  'laboratuvar.aitablo.deger': 'Value',
  'laboratuvar.aitablo.ideal': 'Ideal',
  'laboratuvar.aitablo.parametre': 'Parameter',
  'laboratuvar.aitablo.puan': 'Score',
  'laboratuvar.alan.alkol': 'Alcohol (%vol)',
  'laboratuvar.alan.bulaniklik': 'Turbidity (NTU)',
  'laboratuvar.alan.kalintiseker': 'Residual sugar (g/L)',
  'laboratuvar.alan.malikasit': 'Malic acid (g/L)',
  'laboratuvar.alan.not': 'Note',
  'laboratuvar.alan.numunetur': 'Sample type',
  'laboratuvar.alan.parti': 'Lot',
  'laboratuvar.alan.ph': 'pH',
  'laboratuvar.alan.serbestso2': 'Free SO₂ (mg/L)',
  'laboratuvar.alan.toplamasitlik': 'Total acidity (g/L)',
  'laboratuvar.alan.toplamso2': 'Total SO₂ (mg/L)',
  'laboratuvar.alan.ucucuasitlik': 'Volatile acidity (g/L)',
  'laboratuvar.alan.yogunluk': 'Density',
  'laboratuvar.baslik': 'Laboratory',
  'laboratuvar.bos.numune': 'No sample records.',
  'laboratuvar.bos.sonuc': 'No analysis results.',
  'laboratuvar.bos.sonucipucu': 'Start by taking a sample and entering its results.',
  'laboratuvar.bos.spek': 'No specifications defined.',
  'laboratuvar.bos.spekipucu': 'Specifications are used to check analysis results automatically.',
  'laboratuvar.dugme.aiyorum': 'AI commentary',
  'laboratuvar.dugme.numunal': 'Take sample',
  'laboratuvar.dugme.numunekaydet': 'Save sample and enter results',
  'laboratuvar.dugme.sonucgir': 'Enter result',
  'laboratuvar.dugme.sonuckaydet': 'Save result',
  'laboratuvar.filtre.bekleyen': 'Pending approval',
  'laboratuvar.filtre.onay': 'Approval status',
  'laboratuvar.filtre.onaylanan': 'Approved',
  'laboratuvar.filtre.reddedilen': 'Rejected',
  'laboratuvar.filtre.tumu': 'All results',
  'laboratuvar.kip.aiyorum': 'AI laboratory commentary',
  'laboratuvar.kip.numune': 'Take sample',
  'laboratuvar.kip.sonuc': 'Enter analysis result',
  'laboratuvar.numunetablo.alinma': 'Sampled at',
  'laboratuvar.numunetablo.durum': 'Status',
  'laboratuvar.numunetablo.kod': 'Code',
  'laboratuvar.numunetablo.parti': 'Lot',
  'laboratuvar.numunetablo.sonuc': 'Results',
  'laboratuvar.numunetablo.tank': 'Tank',
  'laboratuvar.numunetablo.tur': 'Type',
  'laboratuvar.numunetur.kontrol': 'Control',
  'laboratuvar.numunetur.rutin': 'Routine',
  'laboratuvar.numunetur.sikayet': 'Complaint',
  'laboratuvar.numunetur.sislemeoncesi': 'Pre-bottling',
  'laboratuvar.rozet.spekdisi': 'Out of spec',
  'laboratuvar.secim.seciniz': 'Select…',
  'laboratuvar.sekme.numune': 'Samples',
  'laboratuvar.sekme.sonuc': 'Analysis Results',
  'laboratuvar.sekme.spek': 'Specifications',
  'laboratuvar.spektablo.alan': 'Field',
  'laboratuvar.spektablo.altsinir': 'Lower limit',
  'laboratuvar.spektablo.birim': 'Unit',
  'laboratuvar.spektablo.parametre': 'Parameter',
  'laboratuvar.spektablo.saraptipi': 'Wine type',
  'laboratuvar.spektablo.seviye': 'Severity',
  'laboratuvar.spektablo.tumu': 'All',
  'laboratuvar.spektablo.ustsinir': 'Upper limit',
  'laboratuvar.tablo.alkol': 'Alcohol',
  'laboratuvar.tablo.islem': 'Action',
  'laboratuvar.tablo.kod': 'Code',
  'laboratuvar.tablo.onay': 'Approval',
  'laboratuvar.tablo.parti': 'Lot',
  'laboratuvar.tablo.ph': 'pH',
  'laboratuvar.tablo.seker': 'Sugar',
  'laboratuvar.tablo.serbestso2': 'Free SO₂',
  'laboratuvar.tablo.ta': 'TA',
  'laboratuvar.tablo.tarih': 'Date',
  'laboratuvar.tablo.toplamso2': 'Total SO₂',
  'laboratuvar.tablo.ua': 'VA',
  'laboratuvar.uyari.redgerekce': 'Rejection reason (required):',
  'laboratuvar.yukleniyor.yorum': 'Interpreting analysis…',
  'pano.ai.aciklama': 'Local analysis · for decision support only',
  'pano.ai.baslik': 'AI suggestions',
  'pano.ai.bos': 'No risk indicators found.',
  'pano.ai.bosipucu': 'All lots are within normal range.',
  'pano.asama.aciklama': 'Active lots',
  'pano.asama.baslik': 'Lot stage distribution',
  'pano.baslik': 'Dashboard',
  'pano.dusukstok.baslik': 'Items below minimum stock',
  'pano.dusukstok.bos': 'No critical stock.',
  'pano.dusukstok.kalem': 'items',
  'pano.dusukstok.link': 'Inventory',
  'pano.dusukstok.tablo.eksik': 'Shortfall',
  'pano.dusukstok.tablo.kalem': 'Item',
  'pano.dusukstok.tablo.mevcut': 'On hand',
  'pano.dusukstok.tablo.minimum': 'Minimum',
  'pano.faaliyet.baslik': 'Recent activity',
  'pano.faaliyet.bos': 'No activity yet.',
  'pano.faaliyet.sistem': 'system',
  'pano.fermantasyon.aktif': 'active fermentations',
  'pano.fermantasyon.baslik': 'Active fermentations',
  'pano.fermantasyon.bos': 'No fermentation in progress.',
  'pano.fermantasyon.gun': 'day',
  'pano.fermantasyon.tahminibitis': 'Estimated completion',
  'pano.fermantasyon.tankyok': 'no tank',
  'pano.gorev.baslik': 'Upcoming operations',
  'pano.gorev.bos': 'No upcoming work.',
  'pano.gorev.gecikti': 'Overdue',
  'pano.gorev.gungecikti': 'days overdue',
  'pano.gorev.gunkaldi': 'days left',
  'pano.songuncelleme': 'Last updated',
  'pano.stok.baslik': 'Inventory value by category',
  'pano.stok.seri': 'Value (TRY)',
  'pano.tank.aktif': 'active tanks',
  'pano.tank.baslik': 'Tank fill levels',
  'pano.tank.bos': 'No tank records.',
  'pano.tank.bosdurum': 'Empty',
  'pano.tank.yerlesim': 'Tank layout',
  'pano.tumu': 'View all',
  'pano.uretim.aciklama': 'Last 30 days',
  'pano.uretim.baslik': 'Daily grape intake (kg)',
  'pano.uretim.seri': 'Grapes (kg)',
  'pano.uyari.acik': 'open alerts',
  'pano.uyari.baslik': 'Critical alerts',
  'pano.uyari.bos': 'No open alerts.',
  'pano.uyari.bosipucu': 'The system is operating normally.',
  'pano.yukleniyor': 'Preparing dashboard…',
  'partidetay.gecmis.baslik': 'Operation history',
  'partidetay.gecmis.bos': 'No records.',
  'partidetay.gerilink': 'Lots',
  'partidetay.izleme.aciklama': 'Drag the nodes and zoom with the scroll wheel',
  'partidetay.izleme.baslik': 'Traceability graph',
  'partidetay.izleme.bos': 'No linkage records yet.',
  'partidetay.izleme.bosipucu': 'The graph builds up as transfers, blends or bottling runs are recorded.',
  'partidetay.izleme.geri': 'Backward (to source)',
  'partidetay.izleme.ileri': 'Forward (to product)',
  'partidetay.izleme.tam': 'Full trace',
  'partidetay.kupaj': 'blend',
  'partidetay.maliyet.aciklama': 'Using default indirect cost rates',
  'partidetay.maliyet.ambalaj': 'Packaging',
  'partidetay.maliyet.baslik': 'Cost breakdown',
  'partidetay.maliyet.enerji': 'Energy',
  'partidetay.maliyet.fire': 'Loss',
  'partidetay.maliyet.genelgider': 'Overhead',
  'partidetay.maliyet.iscilik': 'Labour',
  'partidetay.maliyet.katki': 'Additives',
  'partidetay.maliyet.litrebasi': 'Per litre',
  'partidetay.maliyet.toplam': 'Total cost',
  'partidetay.maliyet.uzum': 'Grapes',
  'partidetay.maliyet.yetkiyok': 'You are not authorised to view costs.',
  'partidetay.ozet.alkol': 'Alcohol',
  'partidetay.ozet.asama': 'Stage',
  'partidetay.ozet.durum': 'Status',
  'partidetay.ozet.hacim': 'Volume',
  'partidetay.ozet.ph': 'pH',
  'partidetay.ozet.tank': 'Tank',
  'partidetay.qrkodu': 'QR code',
  'partidetay.rekoltesi': 'vintage',
  'partidetay.risk.aciklama': 'Local numerical analysis · for decision support only',
  'partidetay.risk.baslik': 'Risk assessment',
  'partidetay.tur.fici': 'Barrel',
  'partidetay.tur.kabul': 'Grape intake',
  'partidetay.tur.parti': 'Lot',
  'partidetay.tur.siseleme': 'Bottling',
  'partidetay.tur.tank': 'Tank',
  'partiler.aciklama': 'Production lots traceable from grape to bottle',
  'partiler.arama': 'Search lot code or name…',
  'partiler.baslik': 'Lots',
  'partiler.bos': 'No lot records.',
  'partiler.bosipucu': 'Start by creating a lot from grape intake records.',
  'partiler.dugme.olustur': 'Create lot',
  'partiler.filtre.arialabel': 'Filter by stage',
  'partiler.filtre.tumasamalar': 'All stages',
  'partiler.form.ad': 'Lot name',
  'partiler.form.adornek': 'Öküzgözü Reserve 2026',
  'partiler.form.agirlikipucu': 'kg',
  'partiler.form.hacim': 'Initial volume (L)',
  'partiler.form.hacimipucu': 'Must volume',
  'partiler.form.kabulsec': 'Select intake…',
  'partiler.form.kaynakbaslik': 'Source grape intakes',
  'partiler.form.kaynakekle': 'Add source',
  'partiler.form.satirkaldir': 'Remove row',
  'partiler.form.siraipucu': 'must L',
  'partiler.form.tank': 'Tank',
  'partiler.form.tip': 'Wine type',
  'partiler.hata.kaynakyok': 'At least one grape intake record must be selected.',
  'partiler.kip.baslik': 'Create lot from grape intakes',
  'partiler.rozet.kupaj': 'Blend',
  'partiler.tablo.ad': 'Lot name',
  'partiler.tablo.alkol': 'Alcohol',
  'partiler.tablo.asama': 'Stage',
  'partiler.tablo.cesit': 'Variety',
  'partiler.tablo.durum': 'Status',
  'partiler.tablo.hacim': 'Volume (L)',
  'partiler.tablo.kod': 'Code',
  'partiler.tablo.rekolte': 'Vintage',
  'partiler.tablo.tank': 'Tank',
  'partiler.tablo.tip': 'Type',
  'partiler.tip.beyaz': 'White',
  'partiler.tip.kirmizi': 'Red',
  'partiler.tip.kopuklu': 'Sparkling',
  'partiler.tip.rose': 'Rosé',
  'partiler.tip.tatli': 'Sweet',
  'raporlar.aciklama': 'Production performance, cost analysis and export',
  'raporlar.baslik': 'Reports',
  'raporlar.birim.sise': 'bottles',
  'raporlar.disaaktar.aciklama': 'Download as Excel, CSV or PDF · every download is written to the audit log',
  'raporlar.disaaktar.baslik': 'Export',
  'raporlar.disaaktar.yetkiyok': 'You do not have export permission.',
  'raporlar.grafik.aylik': 'Monthly grape intake',
  'raporlar.grafik.cesit': 'Grape intake by variety',
  'raporlar.maliyet.ad': 'Name',
  'raporlar.maliyet.baslik': 'Lot cost summary',
  'raporlar.maliyet.bos': 'No lots available for costing.',
  'raporlar.maliyet.fire': 'Loss',
  'raporlar.maliyet.hacim': 'Volume (L)',
  'raporlar.maliyet.parti': 'Lot',
  'raporlar.maliyet.rekolte': 'Vintage',
  'raporlar.maliyet.sise': 'Bottles',
  'raporlar.maliyet.toplammaliyet': 'Total cost',
  'raporlar.maliyet.tryl': 'TRY/L',
  'raporlar.maliyet.trysise': 'TRY/bottle',
  'raporlar.ozet.aktifparti': 'Active lots',
  'raporlar.ozet.kabulsayisi': 'Intake count',
  'raporlar.ozet.siselenen': 'Bottled',
  'raporlar.ozet.uzumkabulu': 'Grape intake',
  'raporlar.ozet.verim': 'Yield',
  'raporlar.rapor.fermantasyon.aciklama': 'Start/end, yeast, measurement count',
  'raporlar.rapor.fermantasyon.ad': 'Fermentation',
  'raporlar.rapor.laboratuvar.aciklama': 'All parameters and approval status',
  'raporlar.rapor.laboratuvar.ad': 'Laboratory analyses',
  'raporlar.rapor.maliyet.aciklama': 'Grapes, additives, packaging and overheads',
  'raporlar.rapor.maliyet.ad': 'Lot-based cost',
  'raporlar.rapor.stok.aciklama': 'On-hand quantity, minimum stock, value',
  'raporlar.rapor.stok.ad': 'Inventory status',
  'raporlar.rapor.uretim.aciklama': 'Weighbridge records, quality and amounts',
  'raporlar.rapor.uretim.ad': 'Grape intake / production',
  'recete.aciklama': 'Product recipes, blend scenarios and authorized approval',
  'recete.alan.hacim': 'Volume (L)',
  'recete.alan.hedeftank': 'Target tank',
  'recete.alan.senaryoadi': 'Scenario name',
  'recete.alan.sonucparti': 'Result lot name',
  'recete.baslik': 'Recipes and Blending',
  'recete.bilesen.baslik': 'Component lots (at least 2)',
  'recete.birim.gun': 'days',
  'recete.bos.kupaj': 'No blend scenarios.',
  'recete.bos.kupajipucu': 'Create a new blend scenario from at least two lots; the system pre-calculates alcohol, pH and cost.',
  'recete.bos.recete': 'No recipes.',
  'recete.dugme.bilesenekle': 'Add component',
  'recete.dugme.senaryo': 'Blend scenario',
  'recete.dugme.senaryoolustur': 'Create scenario',
  'recete.dugme.uygula': 'Execute blend',
  'recete.dugme.uygulaonay': 'Execute',
  'recete.hata.enazikibilesen': 'A blend must contain at least two components.',
  'recete.kart.bilesen': 'components',
  'recete.kart.hedef': 'target',
  'recete.kart.uygulandi': 'Executed',
  'recete.kip.olustur': 'Create blend scenario',
  'recete.kip.uygula': 'Execute blend',
  'recete.not.tahmin': 'Predictions are volume-weighted; pH is calculated from H⁺ concentration.',
  'recete.olcut.alkol': 'Alcohol',
  'recete.olcut.maliyet': 'Cost',
  'recete.olcut.ph': 'pH',
  'recete.olcut.ta': 'TA',
  'recete.recetetablo.bilesen': 'Component',
  'recete.recetetablo.maliyet': 'Cost',
  'recete.recetetablo.oranmiktar': 'Share/Amount',
  'recete.recetetablo.tur': 'Type',
  'recete.secim.bos': 'free',
  'recete.secim.partiseciniz': 'Select lot…',
  'recete.sekme.kupaj': 'Blend Scenarios',
  'recete.sekme.recete': 'Recipes',
  'recete.tablo.hacim': 'Volume (L)',
  'recete.tablo.kaynakparti': 'Source lot',
  'recete.tablo.oran': 'Share',
  'recete.uygula.not': 'Executing creates a new lot; the volumes of the source lots are reduced and traceability links are established automatically. This action cannot be undone.',
  'recete.varsayilan.kupajeki': 'blend',
  'saraptipi.beyaz': 'White',
  'saraptipi.kirmizi': 'Red',
  'saraptipi.kopuklu': 'Sparkling',
  'saraptipi.rose': 'Rosé',
  'saraptipi.tatli': 'Sweet',
  'siseleme.aciklama': 'Bottling orders, line tracking, LOT number and label preview',
  'siseleme.alan.barkod': 'Barcode',
  'siseleme.alan.fire': 'Loss (L)',
  'siseleme.alan.hatkodu': 'Line code',
  'siseleme.alan.hedefdepo': 'Target warehouse',
  'siseleme.alan.kalitenotu': 'QC note',
  'siseleme.alan.koliadedi': 'Bottles per case',
  'siseleme.alan.parti': 'Lot',
  'siseleme.alan.planlanansise': 'Planned bottles',
  'siseleme.alan.rededilen': 'Rejected',
  'siseleme.alan.sisehacmi': 'Bottle volume (ml)',
  'siseleme.alan.uretilensise': 'Bottles produced',
  'siseleme.alan.urunadi': 'Product name',
  'siseleme.ambalaj.baslik': 'Packaging components (will be deducted from inventory)',
  'siseleme.ambalaj.etiket': 'Label',
  'siseleme.ambalaj.kapsul': 'Capsule',
  'siseleme.ambalaj.koli': 'Case',
  'siseleme.ambalaj.mantar': 'Cork / closure',
  'siseleme.ambalaj.sise': 'Bottle',
  'siseleme.baslik': 'Bottling and Packaging',
  'siseleme.bitir.not': 'Finishing deducts packaging inventory, receives the finished goods into the warehouse and updates the lot volume.',
  'siseleme.bos.ipucu': 'Create an order by selecting a lot ready for bottling.',
  'siseleme.bos.kayit': 'No bottling orders.',
  'siseleme.dugme.bitir': 'Finish bottling',
  'siseleme.dugme.emir': 'Bottling order',
  'siseleme.dugme.emirolustur': 'Create order',
  'siseleme.dugme.etiket': 'Label preview',
  'siseleme.dugme.hatbaslat': 'Start line',
  'siseleme.dugme.qr': 'QR code',
  'siseleme.dugme.tamamla': 'Complete bottling',
  'siseleme.etiket.uyari': 'This preview does not cover all legal labelling requirements; it must be checked against the regulations before printing.',
  'siseleme.kip.bitir': 'Finish bottling',
  'siseleme.kip.emir': 'Create bottling order',
  'siseleme.kip.etiket': 'Label preview',
  'siseleme.onay.kalitekontrol': 'Passed quality control',
  'siseleme.secim.seciniz': 'Select…',
  'siseleme.secim.varsayilandepo': 'Default warehouse',
  'siseleme.tablo.durum': 'Status',
  'siseleme.tablo.emir': 'Order',
  'siseleme.tablo.fire': 'Scrap',
  'siseleme.tablo.hat': 'Line',
  'siseleme.tablo.islem': 'Action',
  'siseleme.tablo.lotno': 'LOT no',
  'siseleme.tablo.parti': 'Lot',
  'siseleme.tablo.planlanan': 'Planned',
  'siseleme.tablo.uretilen': 'Produced',
  'siseleme.tablo.urun': 'Product',
  'siseleme.tablo.verim': 'Yield',
  'stok.aciklama': 'Raw material, packaging and finished goods inventory · FIFO/FEFO enabled',
  'stok.baslik': 'Inventory & Shipping',
  'stok.dugme.cikis': 'Issue',
  'stok.dugme.giris': 'Receipt',
  'stok.dugme.sayim': 'Count',
  'stok.dugme.transfer': 'Transfer',
  'stok.filtre.kategori': 'Category',
  'stok.form.birimmaliyet': 'Unit cost (TRY)',
  'stok.form.depo': 'Warehouse',
  'stok.form.hedefdepo': 'Destination warehouse',
  'stok.form.kalem': 'Stock item',
  'stok.form.kaynakdepo': 'Source warehouse',
  'stok.form.miktar': 'Quantity',
  'stok.form.not': 'Note',
  'stok.form.particodu': 'Lot code',
  'stok.form.particoduipucu': 'Generated automatically if left blank',
  'stok.form.sayilanmiktar': 'Counted quantity',
  'stok.form.seciniz': 'Select…',
  'stok.form.skt': 'Expiry date',
  'stok.hareket.birimmaliyet': 'Unit cost',
  'stok.hareket.depo': 'Warehouse',
  'stok.hareket.kalem': 'Item',
  'stok.hareket.kullanici': 'User',
  'stok.hareket.miktar': 'Quantity',
  'stok.hareket.tarih': 'Date',
  'stok.hareket.tur': 'Type',
  'stok.hareket.tutar': 'Amount',
  'stok.kategori.ambalaj': 'Packaging',
  'stok.kategori.bitmisurun': 'Finished goods',
  'stok.kategori.hammadde': 'Raw material',
  'stok.kategori.katki': 'Additive',
  'stok.kategori.sarf': 'Consumable',
  'stok.kategori.tumu': 'All categories',
  'stok.kategori.yedekparca': 'Spare part',
  'stok.kip.cikis': 'Stock issue (FIFO/FEFO)',
  'stok.kip.giris': 'Stock receipt',
  'stok.kip.sayim': 'Stock count adjustment',
  'stok.kip.transfer': 'Inter-warehouse transfer',
  'stok.satinalma.aratoplam': 'Subtotal',
  'stok.satinalma.bos': 'No purchase orders.',
  'stok.satinalma.durum': 'Status',
  'stok.satinalma.geneltoplam': 'Grand total',
  'stok.satinalma.kalem': 'Lines',
  'stok.satinalma.siparistarihi': 'Order date',
  'stok.satinalma.tedarikci': 'Supplier',
  'stok.sekme.hareket': 'Movements',
  'stok.sekme.satinalma': 'Purchasing',
  'stok.sekme.seviye': 'Stock Levels',
  'stok.sekme.sevkiyat': 'Shipping',
  'stok.seviye.bos': 'No stock items.',
  'stok.seviye.deger': 'Value',
  'stok.seviye.depolar': 'Warehouses',
  'stok.seviye.kalem': 'Item',
  'stok.seviye.kategori': 'Category',
  'stok.seviye.mevcut': 'On hand',
  'stok.seviye.min': 'Min.',
  'stok.seviye.skt': 'Expiry',
  'stok.sevkiyat.bos': 'No shipment records.',
  'stok.sevkiyat.durum': 'Status',
  'stok.sevkiyat.musteri': 'Customer',
  'stok.sevkiyat.siparis': 'Order',
  'stok.sevkiyat.tasiyici': 'Carrier',
  'stok.sevkiyat.tutar': 'Amount',
  'stok.tablo.kod': 'Code',
  'tablo.sayfalama.kayit': 'records',
  'tablo.sayfalama.onceki': 'Previous page',
  'tablo.sayfalama.sayfa': 'page',
  'tablo.sayfalama.sonraki': 'Next page',
  'tanklar.baslik': 'Tanks',
  'tanklar.bolge.tank': 'tanks',
  'tanklar.bos': 'No tank records.',
  'tanklar.dugme.kaydet': 'Save transfer',
  'tanklar.dugme.transfer': 'Transfer',
  'tanklar.form.fire': 'Loss (L)',
  'tanklar.form.hacim': 'Volume (L)',
  'tanklar.form.hedefipucu': 'Leave empty when emptying',
  'tanklar.form.hedeftank': 'Destination tank',
  'tanklar.form.islemturu': 'Operation type',
  'tanklar.form.kaynakipucu': 'Leave empty for a fill',
  'tanklar.form.kaynaktank': 'Source tank',
  'tanklar.form.lbos': 'L free',
  'tanklar.form.ldolu': 'L filled',
  'tanklar.form.not': 'Note',
  'tanklar.form.parti': 'Lot',
  'tanklar.form.seciniz': 'Select…',
  'tanklar.gorunum.liste': 'List',
  'tanklar.gorunum.yerlesim': 'Layout',
  'tanklar.ipucu.baslik': 'Tip',
  'tanklar.ipucu.metin': 'During a transfer the system automatically checks for sufficient volume in the source tank, sufficient free capacity in the destination tank, and the cleaning status. A dirty tank cannot be filled; a cleaning record must be entered first.',
  'tanklar.islem.aktarma': 'Racking',
  'tanklar.islem.bosaltim': 'Emptying',
  'tanklar.islem.dolum': 'Fill (into tank)',
  'tanklar.islem.tankarasi': 'Tank-to-tank transfer',
  'tanklar.kip.baslik': 'Tank transfer',
  'tanklar.ozet.doluluk': 'fill',
  'tanklar.ozet.toplam': 'Total',
  'tanklar.tablo.bolge': 'Zone',
  'tanklar.tablo.dolu': 'Filled (L)',
  'tanklar.tablo.doluluk': 'Fill level',
  'tanklar.tablo.durum': 'Status',
  'tanklar.tablo.kapasite': 'Capacity (L)',
  'tanklar.tablo.kod': 'Code',
  'tanklar.tablo.parti': 'Lot',
  'tanklar.tablo.sontemizlik': 'Last cleaned',
  'tanklar.tablo.temizlik': 'Cleaning',
  'tanklar.tablo.tip': 'Type',
  'tanklar.tank.dolu': 'full',
  'yapayzeka.aciklama': 'Local model (LM Studio), Claude and NVIDIA providers in a single interface',
  'yapayzeka.alan.gorev': 'Task type',
  'yapayzeka.alan.model': 'Model',
  'yapayzeka.alan.partiler': 'Lots',
  'yapayzeka.alan.saglayici': 'Provider',
  'yapayzeka.analiz.bakim_tahmin': 'Maintenance due forecast',
  'yapayzeka.analiz.rapor': 'Natural language report',
  'yapayzeka.analiz.stok_tahmin': 'Stock depletion forecast',
  'yapayzeka.baglam.panoekle': 'Include overall operations status',
  'yapayzeka.baglam.rag': 'Use document search (RAG)',
  'yapayzeka.baslik': 'AI Workbench',
  'yapayzeka.bos.ipucu': 'Start by typing a question below. If the provider is disabled the system will let you know; the application keeps running.',
  'yapayzeka.bos.metin': 'No conversation selected yet.',
  'yapayzeka.dugme.gonder': 'Send',
  'yapayzeka.gizlilik.harici': 'External cloud provider. Your approval of the data scope is required before any winery data is sent.',
  'yapayzeka.gizlilik.yerel': 'Local model — data never leaves this computer.',
  'yapayzeka.gorev.dokumantasyon': 'Documentation writer',
  'yapayzeka.gorev.genel': 'General',
  'yapayzeka.gorev.hata_teshis': 'Fault diagnosis specialist',
  'yapayzeka.gorev.kalite_kontrol': 'Quality control assistant',
  'yapayzeka.gorev.kod_gelistirici': 'Code developer',
  'yapayzeka.gorev.rapor_yazari': 'Report writer',
  'yapayzeka.gorev.saraphane_danismani': 'Winery consultant',
  'yapayzeka.gorev.veri_analisti': 'Data analyst',
  'yapayzeka.kapsam.ad': 'Name',
  'yapayzeka.kapsam.alanlar': 'Fields to be sent',
  'yapayzeka.kapsam.baslik': 'Data scope to be sent',
  'yapayzeka.kapsam.karakter': 'characters will be sent. For sensitive data you may prefer the local model (LM Studio).',
  'yapayzeka.kapsam.kod': 'Code',
  'yapayzeka.kapsam.onayla': 'I approve, send',
  'yapayzeka.kapsam.tur': 'Type',
  'yapayzeka.kapsam.yaklasik': 'Approximately',
  'yapayzeka.kart.analiz': 'Ready-made analyses',
  'yapayzeka.kart.baglam': 'Data context',
  'yapayzeka.kart.baglamaciklama': 'Winery records to be provided to the model',
  'yapayzeka.kart.kullanim': 'Usage (30 days)',
  'yapayzeka.kart.saglayici': 'Provider and task',
  'yapayzeka.kart.sohbet': 'Chat',
  'yapayzeka.kullanim.cikis': 'output',
  'yapayzeka.kullanim.giris': 'input',
  'yapayzeka.kullanim.hataadet': 'failed',
  'yapayzeka.kullanim.istek': 'Total requests:',
  'yapayzeka.kullanim.istekadet': 'requests',
  'yapayzeka.kullanim.maliyet': 'Estimated cost:',
  'yapayzeka.kullanim.token': 'Tokens:',
  'yapayzeka.model.varsayilan': 'Default',
  'yapayzeka.saglayici.kapali': 'disabled',
  'yapayzeka.saglayici.otomatik': 'Automatic (by task)',
  'yapayzeka.sohbet.konusmano': 'Conversation',
  'yapayzeka.sohbet.saniye': 's',
  'yapayzeka.sohbet.token': 'tokens',
  'yapayzeka.sohbet.yanitliyor': 'Model is responding…',
  'yapayzeka.sohbet.yenigorev': 'Start a new task — responses are for decision support only',
  'yapayzeka.sohbet.yenikonusma': 'New conversation',
  'yapayzeka.sohbet.yertutucu': 'E.g. Volatile acidity is rising in lot PRT-2025-0002, what should I do?',
  'yapayzeka.uyari.oncesi': 'AI outputs are',
  'yapayzeka.uyari.sonrasi': 'in nature. Critical production values cannot be changed by AI; every change requires approval by an authorised user.',
  'yapayzeka.uyari.vurgu': 'decision support',
  'yedekleme.aciklama': 'A consistent copy of the database · complete even in WAL mode',
  'yedekleme.baslik': 'Backup',
  'yedekleme.bilgi.kopya1': 'The backup file is',
  'yedekleme.bilgi.kopya2': ': it contains password hashes, encrypted API keys and the audit log. For this reason downloading requires a separate permission, and every download is written to the audit log.',
  'yedekleme.bilgi.kopyavurgu': 'a copy of the entire database',
  'yedekleme.bilgi.ortam1': 'Regularly copy your backups to',
  'yedekleme.bilgi.ortam2': '— a backup on the same disk is lost together with it when that disk fails.',
  'yedekleme.bilgi.ortamvurgu': 'a different physical medium',
  'yedekleme.bos.ipucu': 'Create the first backup before you start entering production data.',
  'yedekleme.bos.metin': 'No backup has been created yet.',
  'yedekleme.disk.azaliyor': 'Disk space running low',
  'yedekleme.disk.bosalan': 'Free disk space',
  'yedekleme.disk.boyut': 'Size of backups',
  'yedekleme.disk.konum': 'Location',
  'yedekleme.disk.sayi': 'Backup count',
  'yedekleme.dugme.al': 'Create backup',
  'yedekleme.dugme.aliniyor': 'Creating backup…',
  'yedekleme.dugme.indir': 'Download',
  'yedekleme.dugme.temizle': 'Purge old backups',
  'yedekleme.dugme.temizleipucu': 'Delete old backups per the retention policy',
  'yedekleme.kart.liste': 'Backups',
  'yedekleme.kart.siralama': 'Newest first',
  'yedekleme.kip.silbaslik': 'Delete backup',
  'yedekleme.kip.silmetin': 'will be permanently deleted. This action cannot be undone.',
  'yedekleme.secenek.belgeler': 'Archive documents as well',
  'yedekleme.tablo.boyut': 'Size',
  'yedekleme.tablo.dosya': 'File',
  'yedekleme.tablo.islem': 'Actions',
  'yedekleme.tablo.olusturma': 'Created',
  'yedekleme.tablo.tur': 'Type',
  'yedekleme.tur.belgeler': 'Documents',
  'yedekleme.tur.veritabani': 'Database',
  'yedekleme.uyari.yetkiyok': 'You do not have permission to download backup files. Backups are kept on the server; the download permission rests with the system administrator.',
  'grup.genel': 'General',
  'grup.uretim': 'Production',
  'grup.kalite': 'Quality',
  'grup.lojistik': 'Logistics',
  'grup.analiz': 'Analysis',
  'grup.ai': 'AI',
  'grup.sistem': 'System',
  'kpi.aktif_parti': 'Active lots',
  'kpi.toplam_hacim': 'Total wine volume',
  'kpi.fermantasyon': 'Fermentations in progress',
  'kpi.tank_doluluk': 'Tank fill rate',
  'kpi.uzum_kabul': 'Grape intake (last 30 days)',
  'kpi.sise': 'Bottles produced',
  'kpi.uyari': 'Open alerts',
  'kpi.lab_onay': 'Analyses awaiting approval',
}
