/**
 * Türkçe sözlük.
 *
 * Anahtar biçimi: `<sayfa>.<bölüm>.<alan>` — küçük harf, nokta ayraçlı,
 * Türkçe karakter içermez. `genel.*` anahtarları tüm sayfalarda paylaşılır;
 * yeni bir sayfa eklerken önce buraya bakın, aynı metni ikinci kez tanımlamayın.
 *
 * İngilizce karşılığı `en.ts` içindedir. İki sözlüğün anahtar kümesi aynı
 * olmalıdır; `tests`/`ceviri-butunlugu` bunu doğrular.
 */
export const TR: Record<string, string> = {
  // ------------------------------------------------------------------ genel
  'app.ad': 'Akıllı Şaraphane Yönetim Sistemi',
  'app.oturumdogrulaniyor': 'Oturum doğrulanıyor…',
  'app.kisa': 'Şaraphane',
  'genel.kaydet': 'Kaydet',
  'genel.iptal': 'İptal',
  'genel.sil': 'Sil',
  'genel.duzenle': 'Düzenle',
  'genel.yeni': 'Yeni',
  'genel.ara': 'Ara…',
  'genel.yukleniyor': 'Yükleniyor…',
  'genel.kayityok': 'Kayıt bulunamadı.',
  'genel.hata': 'Hata',
  'genel.kapat': 'Kapat',
  'genel.onayla': 'Onayla',
  'genel.reddet': 'Reddet',
  'genel.detay': 'Detay',
  'genel.geri': 'Geri',
  'genel.toplam': 'Toplam',
  'genel.vazgec': 'Vazgeç',
  'genel.tumu': 'Tümü',
  'genel.evet': 'Evet',
  'genel.hayir': 'Hayır',
  'genel.tarih': 'Tarih',
  'genel.durum': 'Durum',
  'genel.kod': 'Kod',
  'genel.ad': 'Ad',
  'genel.aciklama': 'Açıklama',
  'genel.islem': 'İşlem',
  'genel.yetkiyok': 'Bu sayfayı görüntüleme yetkiniz yok.',
  'genel.yetkiyok.ipucu':
    'Gerekli yetki için sistem yöneticinize başvurun. Bu deneme denetim günlüğüne kaydedilir.',
  'genel.sayfabulunamadi': 'Sayfa bulunamadı.',
  'genel.sayfabulunamadi.ipucu': 'Adres yanlış olabilir; menüden bir bölüm seçin.',

  // ------------------------------------------------------------------ giriş
  'giris.baslik': 'Oturum Aç',
  'giris.kullanici': 'Kullanıcı adı veya e-posta',
  'giris.parola': 'Parola',
  'giris.gonder': 'Giriş yap',

  // -------------------------------------------------------------------- menü
  'menu.pano': 'Kontrol Paneli',
  'menu.bag': 'Bağ ve Üzüm Kabulü',
  'menu.parti': 'Partiler',
  'menu.tank': 'Tanklar',
  'menu.fermantasyon': 'Fermantasyon',
  'menu.lab': 'Laboratuvar',
  'menu.recete': 'Reçete ve Kupaj',
  'menu.fici': 'Fıçı ve Mahzen',
  'menu.siseleme': 'Şişeleme',
  'menu.stok': 'Stok ve Sevkiyat',
  'menu.bakim': 'Bakım ve Temizlik',
  'menu.rapor': 'Raporlar',
  'menu.istatistik': 'İstatistikler',
  'menu.yedekleme': 'Yedekleme',
  'menu.ai': 'Yapay Zekâ Merkezi',
  'menu.terminal': 'AI Terminali',
  'menu.denetim': 'Denetim Günlüğü',
  'menu.kullanici': 'Kullanıcılar',
  'menu.ayarlar': 'Ayarlar',
  'menu.egitim': 'Eğitim ve Kılavuz',

  // -------------------------------------------------------------- kabuk/üst
  'kabuk.altbaslik': 'Yönetim Sistemi',
  'kabuk.menudaralt': 'Menüyü daralt/genişlet',
  'kabuk.dil': 'Dil',
  'kabuk.tema': 'Temayı değiştir',
  'kabuk.cikis': 'Oturumu kapat',
  'kabuk.uyari': 'Açık uyarılar',
  'kabuk.altbilgi': 'Yapay zekâ çıktıları karar destek amaçlıdır.',

  // ------------------------------------------------------------ eğitim
  'egitim.baslik': 'Eğitim ve Kullanım Kılavuzu',
  'egitim.aciklama':
    'Rol bazlı, adım adım modüller · her modül gerçek ekranlara bağlantı verir',
  'egitim.sadecerolum': 'Yalnızca rolüme uygun',
  'egitim.ekip': 'Ekip durumu',
  'egitim.ekipdurumu': 'Ekip eğitim durumu',
  'egitim.ekipaciklama':
    'Kimin hangi eğitimi tamamladığı · gıda güvenliği denetiminde sorulur',
  'egitim.kisi': 'Kişi',
  'egitim.rol': 'Rol',
  'egitim.tamamlanan': 'Tamamlanan',
  'egitim.denenen': 'Denenen',
  'egitim.genelilerleme': 'Genel ilerleme',
  'egitim.modulyok': 'Rolünüze uygun eğitim modülü bulunamadı.',
  'egitim.modulyok.ipucu': 'Tüm modülleri görmek için filtreyi kaldırın.',
  'egitim.dakika': 'dk',
  'egitim.adim': 'Adım',
  'egitim.soru': 'soru',
  'egitim.soruda': 'soruda',
  'egitim.dogru': 'doğru',
  'egitim.tumumoduller': 'Tüm modüller',
  'egitim.ekranaGit': 'Ekrana git',
  'egitim.ileri': 'İleri',
  'egitim.sinav': 'Sınav',
  'egitim.sinavaciklama': 'Tüm soruları yanıtlayın; geçme notu %70',
  'egitim.sinavabasla': 'Sınava başla',
  'egitim.sinavibitir': 'Sınavı bitir',
  'egitim.sonuc': 'Sınav sonucu',
  'egitim.gecti': 'Başarılı',
  'egitim.kaldi': 'Tekrar deneyin',
  'egitim.dogrucevap': 'Doğru cevap',
  'egitim.tekrar': 'Tekrar dene',
  'egitim.bitir': 'Bitir',

  // ------------------------------------------- sayfa çevirileri
  'aiterminal.aciklama': 'Plan → onay → Git kontrol noktası → çalıştır → test → birleştir/geri al',
  'aiterminal.alan.dosyalar': 'Etkilenecek dosyalar',
  'aiterminal.alan.dosyalaripucu': 'Her satıra bir göreli yol',
  'aiterminal.alan.istek': 'Ne yapılmasını istiyorsunuz?',
  'aiterminal.alan.istekyertutucu': 'Örn: Fermantasyon ölçüm ekranına yoğunluk grafiği ekle ve testlerini yaz.',
  'aiterminal.alan.komutlar': 'Çalıştırılacak komutlar',
  'aiterminal.alan.komutlaripucu': 'Her satıra bir komut',
  'aiterminal.alan.llmkullan': 'Dil modelinden plan iste',
  'aiterminal.baslik': 'AI Terminali / Geliştirici Ajanı',
  'aiterminal.bos.gorevyok': 'Görev yok.',
  'aiterminal.bos.secilmedi': 'Görev seçilmedi.',
  'aiterminal.bos.secilmediipucu': 'Soldan bir görev seçin veya yeni plan oluşturun. Hiçbir komut onayınız olmadan çalıştırılmaz.',
  'aiterminal.calisma.cikis': 'çıkış',
  'aiterminal.calisma.engellendi': 'engellendi',
  'aiterminal.calisma.zamanasimi': 'zaman aşımı',
  'aiterminal.denetle.engellendi': 'ENGELLENDİ',
  'aiterminal.denetle.yertutucu': 'Komutu çalıştırmadan denetle: python -m pytest -q',
  'aiterminal.dogrulama.basarisiz': 'Testler başarısız',
  'aiterminal.dogrulama.gecti': 'Testler geçti',
  'aiterminal.dugme.calistir': '3. Komutları çalıştır',
  'aiterminal.dugme.denetle': 'Denetle',
  'aiterminal.dugme.dogrula': '4. Lint + test çalıştır',
  'aiterminal.dugme.gerial': 'Geri al',
  'aiterminal.dugme.onayla': '2. Onayla (kontrol noktası oluştur)',
  'aiterminal.dugme.planolustur': 'Plan oluştur',
  'aiterminal.gorev.dal': 'dal',
  'aiterminal.gorev.engellendi': 'Bu plan güvenlik politikası tarafından engellendi.',
  'aiterminal.gorev.komutdenetimi': 'Komut denetimi',
  'aiterminal.gorev.kontrolnoktasi': 'Kontrol noktası:',
  'aiterminal.gorev.planadimlari': 'Plan adımları',
  'aiterminal.guvenlik.calismaalani': 'Çalışma alanı',
  'aiterminal.guvenlik.degisiklikvar': 'değişiklik var',
  'aiterminal.guvenlik.depodegil': 'Depo değil',
  'aiterminal.guvenlik.engellenenislemler': 've engellenen işlemler',
  'aiterminal.guvenlik.engelli': 'Engelli',
  'aiterminal.guvenlik.evet': 'Evet',
  'aiterminal.guvenlik.hayir': 'Hayır',
  'aiterminal.guvenlik.izinli': 'İzinli',
  'aiterminal.guvenlik.izinliaraclar': 'İzin verilen araçlar',
  'aiterminal.guvenlik.onayzorunlu': 'Onay zorunlu',
  'aiterminal.guvenlik.saniye': 'sn',
  'aiterminal.guvenlik.sinir': 'Zaman aşımı / çıktı sınırı',
  'aiterminal.kart.ciktilar': 'Komut çıktıları',
  'aiterminal.kart.diff': 'Değişiklik farkı (diff)',
  'aiterminal.kart.dogrulama': 'Doğrulama sonuçları',
  'aiterminal.kart.gecmis': 'Görev geçmişi',
  'aiterminal.kart.guvenlik': 'Güvenlik sınırları',
  'aiterminal.kart.guvenlikaciklama': 'Bu kısıtlar kod düzeyinde uygulanır ve yapay zekâ tarafından değiştirilemez',
  'aiterminal.kart.plan': '1. Adım — Plan oluştur',
  'aiterminal.uyari.gerial': 'Değişiklikler kontrol noktasına geri alınacak. Onaylıyor musunuz?',
  'aiterminal.uyari.redgerekce': 'Red gerekçesi:',
  'asama.dinlendirme': 'Dinlendirme',
  'asama.fermantasyon': 'Fermantasyon',
  'asama.kupaj': 'Kupaj',
  'asama.malolaktik': 'Malolaktik',
  'asama.olgunlastirma': 'Olgunlaştırma',
  'asama.sira': 'Şıra',
  'asama.siseleme': 'Şişeleme',
  'asama.stabilizasyon': 'Stabilizasyon',
  'asama.tamamlandi': 'Tamamlandı',
  'asama.uzum_kabul': 'Üzüm kabul',
  'ayarlar.aciklama': 'Arayüz tercihleri ve yapay zekâ sağlayıcı yapılandırması',
  'ayarlar.alan.cikismaliyet': 'Çıkış maliyeti (1K token)',
  'ayarlar.alan.dil': 'Dil',
  'ayarlar.alan.dilipucu': 'Altyapı çok dilli; yeni diller sözlük eklenerek desteklenir.',
  'ayarlar.alan.girismaliyet': 'Giriş maliyeti (1K token)',
  'ayarlar.alan.modelyertutucu': 'Önce model listesini çekin',
  'ayarlar.alan.seciniz': 'Seçiniz…',
  'ayarlar.alan.sunucu': 'Sunucu adresi',
  'ayarlar.alan.tema': 'Tema',
  'ayarlar.alan.varsayilanmodel': 'Varsayılan model',
  'ayarlar.alan.yenidendeneme': 'Yeniden deneme',
  'ayarlar.alan.zamanasimi': 'Zaman aşımı (sn)',
  'ayarlar.anahtar.parmakizi': 'parmak izi',
  'ayarlar.anahtar.tanimli': 'Anahtar tanımlı',
  'ayarlar.anahtar.tanimsiz': 'API anahtarı tanımlı değil — sağlayıcı kullanılamaz.',
  'ayarlar.baslik': 'Ayarlar',
  'ayarlar.bilgi.anahtaroncesi': 'API anahtarları',
  'ayarlar.bilgi.anahtarsonrasi': 'saklanır (Fernet/AES) ve hiçbir ekranda, günlükte veya API yanıtında açık gösterilmez. Yalnızca yazılabilir; okunamaz. Anahtarın doğruluğunu parmak izinden takip edebilirsiniz.',
  'ayarlar.bilgi.anahtarvurgu': 'şifrelenerek',
  'ayarlar.dugme.baglantitest': 'Bağlantıyı test et',
  'ayarlar.dugme.degistir': 'Değiştir',
  'ayarlar.dugme.ekle': 'Ekle',
  'ayarlar.dugme.modelyenile': 'Model listesini yenile',
  'ayarlar.dugme.sifrelikaydet': 'Şifreleyerek kaydet',
  'ayarlar.dugme.sohbetlitest': 'Sohbetli test',
  'ayarlar.gizlilik.harici': 'Harici bulut',
  'ayarlar.gizlilik.yerel': 'Yerel · veri çıkmaz',
  'ayarlar.kart.arayuz': 'Arayüz',
  'ayarlar.kip.anahtar': 'API anahtarı',
  'ayarlar.kip.bilgioncesi': 'Anahtar tarayıcıdan sunucuya iletilir ve',
  'ayarlar.kip.bilgisonrasi': 'veritabanına yazılır. Bu ekran dışında hiçbir yerde görüntülenmez. Anahtarı e-posta, sohbet veya ekran görüntüsü ile paylaşmayın.',
  'ayarlar.mesaj.anahtarsilindi': 'API anahtarı silindi.',
  'ayarlar.mesaj.kaydedildi': 'Ayar kaydedildi.',
  'ayarlar.mesaj.modelbulundu': 'model bulundu.',
  'ayarlar.mesaj.modelhata': 'Model listesi alınamadı',
  'ayarlar.mesaj.yanit': 'Yanıt',
  'ayarlar.saglayici.durum': 'Durum:',
  'ayarlar.saglayici.etkin': 'Etkin',
  'ayarlar.saglayici.modellistesi': 'model listesi',
  'ayarlar.tema.acik': 'Açık',
  'ayarlar.tema.koyu': 'Koyu',
  'ayarlar.tema.sistem': 'Sistem tercihine uy',
  'ayarlar.uyari.anahtarsil': 'API anahtarı silinsin mi?',
  'ayarlar.uyari.buluttest': 'Bu test bulut sağlayıcıya küçük bir istek gönderir ve az miktarda ücret doğurabilir. Devam edilsin mi?',
  'ayarlar.uyari.yereltest': 'Küçük bir test isteği gönderilecek. Devam?',
  'bag.aciklama': 'Bağ/parsel tanımları, üzüm çeşitleri ve kantar kabul kayıtları',
  'bag.arama.kabul': 'Kod veya plaka ara…',
  'bag.baslik': 'Bağ ve Üzüm Kabulü',
  'bag.bos.bag': 'Bağ kaydı yok.',
  'bag.bos.cesit': 'Üzüm çeşidi tanımlı değil.',
  'bag.bos.kabul': 'Üzüm kabul kaydı yok.',
  'bag.bos.kabulipucu': 'Bağbozumu başladığında ilk kabul kaydını girin.',
  'bag.bos.parsel': 'Parsel kaydı yok.',
  'bag.dugme.kabul': 'Üzüm kabulü',
  'bag.form.asitlik': 'Toplam asitlik (g/L)',
  'bag.form.bag': 'Bağ',
  'bag.form.birimfiyat': 'Birim fiyat (TRY/kg)',
  'bag.form.brix': 'Brix (°Bx)',
  'bag.form.cesit': 'Üzüm çeşidi',
  'bag.form.hasattarihi': 'Hasat tarihi',
  'bag.form.kalite': 'Kalite sınıfı',
  'bag.form.netagirlik': 'Net ağırlık (kg)',
  'bag.form.notlar': 'Notlar',
  'bag.form.parsel': 'Parsel',
  'bag.form.ph': 'pH',
  'bag.form.plaka': 'Araç plakası',
  'bag.form.plakaornek': '35 ABC 123',
  'bag.form.seciniz': 'Seçiniz…',
  'bag.form.sicaklik': 'Sıcaklık (°C)',
  'bag.kalite.a': 'A — Birinci sınıf',
  'bag.kalite.b': 'B — İkinci sınıf',
  'bag.kalite.c': 'C — Üçüncü sınıf',
  'bag.kalite.red': 'Reddedildi',
  'bag.kip.baslik': 'Yeni üzüm kabulü',
  'bag.sekme.bag': 'Bağlar',
  'bag.sekme.cesit': 'Üzüm Çeşitleri',
  'bag.sekme.kabul': 'Üzüm Kabulü',
  'bag.sekme.parsel': 'Parseller',
  'bag.tablo.alan': 'Alan (da)',
  'bag.tablo.bag': 'Bağ',
  'bag.tablo.bagadi': 'Bağ adı',
  'bag.tablo.bolge': 'Bölge',
  'bag.tablo.brix': 'Brix',
  'bag.tablo.cesit': 'Çeşit',
  'bag.tablo.dikim': 'Dikim',
  'bag.tablo.hasat': 'Hasat',
  'bag.tablo.hedefbrix': 'Hedef Brix',
  'bag.tablo.hedefph': 'Hedef pH',
  'bag.tablo.kalite': 'Kalite',
  'bag.tablo.kod': 'Kod',
  'bag.tablo.koy': 'Köy/Mevki',
  'bag.tablo.mense': 'Menşe',
  'bag.tablo.netkg': 'Net kg',
  'bag.tablo.omca': 'Omca',
  'bag.tablo.parsel': 'Parsel',
  'bag.tablo.parselad': 'Parsel',
  'bag.tablo.ph': 'pH',
  'bag.tablo.qr': 'QR',
  'bag.tablo.qrac': 'QR kodunu aç',
  'bag.tablo.rakim': 'Rakım (m)',
  'bag.tablo.renk': 'Renk',
  'bag.tablo.toprak': 'Toprak',
  'bag.tablo.tutar': 'Tutar',
  'bakim.aciklama': 'Ekipman bakımı, arıza kayıtları ve CIP/temizlik doğrulaması',
  'bakim.baslik': 'Bakım ve Temizlik',
  'bakim.birim.gun': 'gün',
  'bakim.dugme.yenikayit': 'Bakım kaydı',
  'bakim.ekipman.ad': 'Ekipman',
  'bakim.ekipman.bos': 'Ekipman kaydı yok.',
  'bakim.ekipman.durum': 'Durum',
  'bakim.ekipman.kalan': 'Kalan',
  'bakim.ekipman.kod': 'Kod',
  'bakim.ekipman.sonbakim': 'Son bakım',
  'bakim.ekipman.sonrakibakim': 'Sonraki bakım',
  'bakim.ekipman.tur': 'Tür',
  'bakim.ekipman.uretici': 'Üretici',
  'bakim.form.aciklama': 'Açıklama',
  'bakim.form.baslik': 'Başlık',
  'bakim.form.cipbaslik': 'CIP ayrıntıları',
  'bakim.form.dogrulandi': 'Temizlik doğrulandı (steril kabul edilecek)',
  'bakim.form.durus': 'Duruş süresi (dk)',
  'bakim.form.ekipman': 'Ekipman',
  'bakim.form.kimyasal': 'Kimyasal',
  'bakim.form.kimyasalornek': 'Kostik %2',
  'bakim.form.maliyet': 'Maliyet (TRY)',
  'bakim.form.sicaklik': 'Sıcaklık (°C)',
  'bakim.form.sure': 'Süre (dk)',
  'bakim.form.tamamlandi': 'İşlem tamamlandı (bitmemiş arıza kaydı ekipmanı "arızalı" yapar)',
  'bakim.form.tank': 'Tank',
  'bakim.form.tankipucu': 'Ekipman veya tank seçilmelidir',
  'bakim.form.tur': 'Kayıt türü',
  'bakim.kayit.baslangic': 'Başlangıç',
  'bakim.kayit.baslik': 'Başlık',
  'bakim.kayit.bitis': 'Bitiş',
  'bakim.kayit.bos': 'Bakım kaydı yok.',
  'bakim.kayit.durus': 'Duruş (dk)',
  'bakim.kayit.ekipman': 'Ekipman',
  'bakim.kayit.kod': 'Kod',
  'bakim.kayit.maliyet': 'Maliyet',
  'bakim.kayit.sorumlu': 'Sorumlu',
  'bakim.kayit.tur': 'Tür',
  'bakim.kip.baslik': 'Bakım / temizlik kaydı',
  'bakim.sekme.ekipman': 'Ekipmanlar',
  'bakim.sekme.kayit': 'Bakım Kayıtları',
  'bakim.tur.ariza': 'Arıza',
  'bakim.tur.cip': 'CIP (yerinde temizlik)',
  'bakim.tur.kalibrasyon': 'Kalibrasyon',
  'bakim.tur.periyodik': 'Periyodik bakım',
  'bakim.tur.temizlik': 'Temizlik',
  'bakim.yaklasan.baslik': 'Yaklaşan ve geciken bakımlar',
  'bakim.yaklasan.durum': 'Durum',
  'bakim.yaklasan.ekipman': 'Ekipman',
  'bakim.yaklasan.gecikmis': 'gecikmiş',
  'bakim.yaklasan.gungecikti': 'gün gecikti',
  'bakim.yaklasan.kalangun': 'Kalan gün',
  'bakim.yaklasan.planlanantarih': 'Planlanan tarih',
  'bakim.yaklasan.tur': 'Tür',
  'bakim.yaklasan.yaklasan': 'yaklaşan',
  'denetim.aciklama': 'Kim, neyi, ne zaman değiştirdi · kayıtlar değiştirilemez ve silinemez',
  'denetim.baslik': 'Denetim Günlüğü',
  'denetim.bos.metin': 'Denetim kaydı yok.',
  'denetim.deger.sistem': 'sistem',
  'denetim.degismezlik.oncesi': 'Denetim kayıtları üzerinde güncelleme veya silme uç noktası bulunmaz; silme denemesi',
  'denetim.degismezlik.sonrasi': 'ile reddedilir. Parola, API anahtarı ve belirteç gibi gizli değerler kaydedilmeden önce otomatik maskelenir.',
  'denetim.detay.degisenalanlar': 'Değişen alanlar',
  'denetim.detay.ip': 'IP adresi',
  'denetim.detay.istek': 'İstek',
  'denetim.detay.kayit': 'Kayıt',
  'denetim.detay.oncekideger': 'Önceki değer',
  'denetim.detay.sonrakideger': 'Sonraki değer',
  'denetim.filtre.tumeylemler': 'Tüm eylemler',
  'denetim.filtre.tumseviyeler': 'Tüm seviyeler',
  'denetim.kart.degismezlik': 'Değişmezlik ilkesi',
  'denetim.kip.baslik': 'Denetim kaydı',
  'denetim.seviye.bilgi': 'Bilgi',
  'denetim.seviye.kritik': 'Kritik',
  'denetim.seviye.uyari': 'Uyarı',
  'denetim.tablo.ai': 'AI',
  'denetim.tablo.eylem': 'Eylem',
  'denetim.tablo.kayitturu': 'Kayıt türü',
  'denetim.tablo.kod': 'Kod',
  'denetim.tablo.kullanici': 'Kullanıcı',
  'denetim.tablo.ozet': 'Özet',
  'denetim.tablo.seviye': 'Seviye',
  'denetim.tablo.zaman': 'Zaman',
  'durum.acik': 'Açık',
  'durum.agir': 'Ağır',
  'durum.ahsap': 'Ahşap',
  'durum.ai_istek': 'AI isteği',
  'durum.ai_oneri': 'AI önerisi',
  'durum.aktif': 'Aktif',
  'durum.alkol': 'Alkol',
  'durum.ambalaj': 'Ambalaj',
  'durum.amerikan': 'Amerikan',
  'durum.amfora': 'Amfora',
  'durum.ariza': 'Arıza',
  'durum.arizali': 'Arızalı',
  'durum.arsiv': 'Arşiv',
  'durum.ayar_degisikligi': 'Ayar değişikliği',
  'durum.bakimda': 'Bakımda',
  'durum.basarili': 'Başarılı',
  'durum.basarisiz': 'Başarısız',
  'durum.beklemede': 'Beklemede',
  'durum.bekliyor': 'Bekliyor',
  'durum.beton': 'Beton',
  'durum.bitmis_urun': 'Bitmiş ürün',
  'durum.bos': 'Boş',
  'durum.calisiyor': 'Çalışıyor',
  'durum.calisiyor_gorev': 'Çalışıyor',
  'durum.cikis': 'Çıkış',
  'durum.cip': 'CIP',
  'durum.cozuldu': 'Çözüldü',
  'durum.devam_ediyor': 'Devam ediyor',
  'durum.devre_disi': 'Devre dışı',
  'durum.diger': 'Diğer',
  'durum.disa_aktar': 'Dışa aktar',
  'durum.dolu': 'Dolu',
  'durum.durakladi': 'Duraklandı',
  'durum.emekli': 'Emekli',
  'durum.fiberglas': 'Fiberglas',
  'durum.filtre': 'Filtre',
  'durum.fire': 'Fire',
  'durum.fransiz': 'Fransız',
  'durum.geri_alindi': 'Geri alındı',
  'durum.giris': 'Giriş',
  'durum.giris_basarisiz': 'Başarısız giriş',
  'durum.guncelle': 'Güncelle',
  'durum.hafif': 'Hafif',
  'durum.hammadde': 'Hammadde',
  'durum.hazirlaniyor': 'Hazırlanıyor',
  'durum.hazirlik': 'Hazırlık',
  'durum.iade': 'İade',
  'durum.ikincil': 'İkincil',
  'durum.iptal': 'İptal',
  'durum.izinsiz_erisim': 'İzinsiz erişim',
  'durum.kafkas': 'Kafkas',
  'durum.kalibrasyon': 'Kalibrasyon',
  'durum.kapandi': 'Kapandı',
  'durum.karantina': 'Karantina',
  'durum.katki': 'Katkı',
  'durum.kismen_dolu': 'Kısmen dolu',
  'durum.kismen_teslim': 'Kısmen teslim',
  'durum.kontrol': 'Kontrol',
  'durum.macar': 'Macar',
  'durum.okundu': 'Okundu',
  'durum.olustur': 'Oluştur',
  'durum.onarimda': 'Onarımda',
  'durum.onay': 'Onay',
  'durum.onay_bekliyor': 'Onay bekliyor',
  'durum.onaylandi': 'Onaylandı',
  'durum.orta_plus': 'Orta+',
  'durum.paslanmaz_celik': 'Paslanmaz çelik',
  'durum.periyodik': 'Periyodik',
  'durum.plan_hazir': 'Plan hazır',
  'durum.planlandi': 'Planlandı',
  'durum.pompa': 'Pompa',
  'durum.pres': 'Pres',
  'durum.red': 'Red',
  'durum.reddedildi': 'Reddedildi',
  'durum.rutin': 'Rutin',
  'durum.sap_ayirici': 'Sap ayırıcı',
  'durum.sarf': 'Sarf malzemesi',
  'durum.sayim': 'Sayım',
  'durum.senaryo': 'Senaryo',
  'durum.sevk_edildi': 'Sevk edildi',
  'durum.sil': 'Sil',
  'durum.siparis_verildi': 'Sipariş verildi',
  'durum.siseleme_hatti': 'Şişeleme hattı',
  'durum.slavonya': 'Slavonya',
  'durum.sogutma': 'Soğutma',
  'durum.tank': 'Tank',
  'durum.taslak': 'Taslak',
  'durum.temizlik': 'Temizlik',
  'durum.temizlikte': 'Temizlikte',
  'durum.terminal_geri_al': 'Terminal geri alma',
  'durum.terminal_komut': 'Terminal komutu',
  'durum.terminal_onay': 'Terminal onayı',
  'durum.terminal_red': 'Terminal reddi',
  'durum.teslim_alindi': 'Teslim alındı',
  'durum.teslim_edildi': 'Teslim edildi',
  'durum.test_ediliyor': 'Test ediliyor',
  'durum.transfer': 'Transfer',
  'durum.uretim_giris': 'Üretim girişi',
  'durum.uretim_tuketim': 'Üretim tüketimi',
  'durum.uygulandi': 'Uygulandı',
  'durum.yedek_parca': 'Yedek parça',
  'durum.yoksayildi': 'Yoksayıldı',
  'fermantasyon.aciklama': 'Günlük ölçümler, eğriler, eşik alarmları ve tahmini bitiş',
  'fermantasyon.alan.baslangicbrix': 'Başlangıç Brix',
  'fermantasyon.alan.brix': 'Brix (°Bx)',
  'fermantasyon.alan.hacim': 'Hacim (L)',
  'fermantasyon.alan.hedefbrix': 'Hedef Brix',
  'fermantasyon.alan.hedefbrixipucu': 'Kuru şaraplarda genellikle -1 ile 0 arası',
  'fermantasyon.alan.makssicaklik': 'Maks. sıcaklık (°C)',
  'fermantasyon.alan.mayasusu': 'Maya suşu',
  'fermantasyon.alan.minsicaklik': 'Min. sıcaklık (°C)',
  'fermantasyon.alan.not': 'Not',
  'fermantasyon.alan.parti': 'Parti',
  'fermantasyon.alan.ph': 'pH',
  'fermantasyon.alan.sapkayonetimi': 'Şapka yönetimi',
  'fermantasyon.alan.serbestso2': 'Serbest SO₂ (mg/L)',
  'fermantasyon.alan.sicaklik': 'Sıcaklık (°C)',
  'fermantasyon.alan.tank': 'Tank',
  'fermantasyon.alan.ucucuasitlik': 'Uçucu asitlik (g/L)',
  'fermantasyon.alan.yogunluk': 'Yoğunluk',
  'fermantasyon.baslik': 'Fermantasyon',
  'fermantasyon.bos.kayit': 'Fermantasyon kaydı yok.',
  'fermantasyon.bos.olcum': 'Henüz ölçüm girilmemiş.',
  'fermantasyon.bos.olcumipucu': 'İlk ölçümü girerek eğriyi başlatın.',
  'fermantasyon.dugme.basla': 'Başlat',
  'fermantasyon.dugme.baslat': 'Fermantasyon başlat',
  'fermantasyon.dugme.olcumgir': 'Ölçüm gir',
  'fermantasyon.dugme.olcumkaydet': 'Ölçümü kaydet',
  'fermantasyon.durum.devamediyor': 'Devam ediyor',
  'fermantasyon.durum.durakladi': 'Duraklandı',
  'fermantasyon.durum.planlandi': 'Planlandı',
  'fermantasyon.durum.tamamlandi': 'Tamamlandı',
  'fermantasyon.filtre.durum': 'Duruma göre filtrele',
  'fermantasyon.filtre.tumu': 'Tüm durumlar',
  'fermantasyon.grafik.anomali': 'ölçümde anomali işaretlendi.',
  'fermantasyon.grafik.brix': 'Brix',
  'fermantasyon.grafik.hedefbrix': 'Hedef Brix',
  'fermantasyon.grafik.ph': 'pH',
  'fermantasyon.grafik.sicaklik': 'Sıcaklık (°C)',
  'fermantasyon.kart.egri': 'fermantasyon eğrisi',
  'fermantasyon.kart.maya': 'maya',
  'fermantasyon.kip.baslat': 'Fermantasyon başlat',
  'fermantasyon.kip.olcum': 'Ölçüm gir',
  'fermantasyon.olcum.ipucu': 'En az bir ölçüm değeri girilmelidir. Hedef sıcaklık aralığı:',
  'fermantasyon.secim.seciniz': 'Seçiniz…',
  'fermantasyon.tablo.anomali': 'Anomali',
  'fermantasyon.tablo.baslangic': 'Başlangıç',
  'fermantasyon.tablo.brix': 'Brix',
  'fermantasyon.tablo.durum': 'Durum',
  'fermantasyon.tablo.ilerleme': 'İlerleme',
  'fermantasyon.tablo.kod': 'Kod',
  'fermantasyon.tablo.parti': 'Parti',
  'fermantasyon.tablo.sicaklik': 'Sıcaklık',
  'fermantasyon.tablo.tank': 'Tank',
  'fermantasyon.tablo.tur': 'Tür',
  'fermantasyon.tahmin.baslik': 'Tahmini bitiş',
  'fermantasyon.tahmin.not': 'Bu tahmin son ölçümlerin doğrusal eğiminden hesaplanır ve karar destek amaçlıdır.',
  'fici.alan.fire': 'Fire (L)',
  'fici.alan.hacim': 'Hacim (L)',
  'fici.alan.islemturu': 'İşlem türü',
  'fici.alan.not': 'Not',
  'fici.alan.parti': 'Parti',
  'fici.baslik': 'Fıçı ve Mahzen',
  'fici.birim.gun': 'gün',
  'fici.birim.yil': 'yıl',
  'fici.bos.kayit': 'Fıçı kaydı yok.',
  'fici.gorunum.harita': 'Mahzen haritası',
  'fici.gorunum.liste': 'Liste',
  'fici.hareket.aktarma': 'Aktarma',
  'fici.hareket.bosaltim': 'Boşaltım',
  'fici.hareket.dolum': 'Dolum',
  'fici.hareket.durum': 'durum',
  'fici.hareket.mevcut': 'Mevcut',
  'fici.hareket.onarim': 'Onarım',
  'fici.hareket.temizlik': 'Temizlik',
  'fici.hareket.topping': 'Üst tamamlama (topping)',
  'fici.kart.fici': 'fıçı',
  'fici.kip.hareket': 'Fıçı hareketi',
  'fici.ozet.dolu': 'fıçı dolu',
  'fici.ozet.toplamfire': 'toplam fire',
  'fici.secim.seciniz': 'Seçiniz…',
  'fici.tablo.dolu': 'Dolu',
  'fici.tablo.durum': 'Durum',
  'fici.tablo.fire': 'Fire (L)',
  'fici.tablo.kapasite': 'Kapasite',
  'fici.tablo.kavurma': 'Kavurma',
  'fici.tablo.kod': 'Kod',
  'fici.tablo.mese': 'Meşe',
  'fici.tablo.olgunlasma': 'Olgunlaşma',
  'fici.tablo.parti': 'Parti',
  'fici.tablo.qr': 'QR',
  'fici.tablo.uretici': 'Üretici',
  'fici.tablo.yas': 'Yaş',
  'giris.hata': 'Giriş yapılamadı.',
  'giris.slogan': 'Bağdan şişeye tüm üretim süreçleri tek panelde',
  'giris.yardim': 'Hesabınız yoksa sistem yöneticinizle iletişime geçin.',
  'giris.ilkkurulum':
    'Ilk kurulum: yönetici parolası kurulum sırasında üretilir ve veri klasöründeki '
    + 'ILK-GIRIS.txt dosyasına bir kez yazılır. İlk girişte değiştirilmesi zorunludur '
    +'ve bu hesap parola değiştirilene kadar yalnızca bu bilgisayardan açılabilir.',
  // ------------------------------------------------------- zorunlu parola
  'parola.zorunlu.baslik': 'Parolanızı değiştirmeniz gerekiyor',
  'parola.zorunlu.aciklama':
    'Bu hesap geçici bir parola ile açıldı. Yeni bir parola belirlemeden pano, '
    + 'üretim verileri, mali kayıtlar, yapay zekâ ayarları, dışa aktarma ve '
    + 'yedekleme ekranları açılmaz.',
  'parola.mevcut': 'Mevcut parola',
  'parola.yeni': 'Yeni parola',
  'parola.tekrar': 'Yeni parola (tekrar)',
  'parola.kural':
    'En az 10 karakter; en az bir büyük harf, bir küçük harf ve bir rakam.',
  'parola.eslesmiyor': 'Yeni parolalar eşleşmiyor.',
  'parola.hata': 'Parola değiştirilemedi. Lütfen bilgileri kontrol edin.',
  'parola.gonder': 'Parolayı değiştir',
  'goreli.dk': 'dk önce',
  'goreli.gun': 'gün önce',
  'goreli.sa': 'sa önce',
  'goreli.simdi': 'az önce',
  'istatistikler.aciklama': 'Verimlilik, kayıp ve kalite tutarlılığı · dönem karşılaştırmalı',
  'istatistikler.bakim.bos': 'Bakım kaydı yok.',
  'istatistikler.bakim.cipdogrulama': 'CIP doğrulama',
  'istatistikler.bakim.cipipucu': 'Gıda güvenliği denetimi',
  'istatistikler.bakim.cipkaydi': 'CIP kaydı',
  'istatistikler.bakim.durus': 'Duruş (dk)',
  'istatistikler.bakim.durusaciklama': 'Bakım türüne göre toplam duruş',
  'istatistikler.bakim.durusbaslik': 'Duruş kaynakları',
  'istatistikler.bakim.ekipman': 'Ekipman',
  'istatistikler.bakim.ekipmanbaslik': 'En çok duran ekipman',
  'istatistikler.bakim.ekipmanbos': 'Ekipman bakım kaydı yok.',
  'istatistikler.bakim.gecikenbakim': 'Geciken bakım',
  'istatistikler.bakim.gecikenipucu': 'Planlanan tarihi geçmiş ekipman',
  'istatistikler.bakim.kayit': 'Kayıt',
  'istatistikler.baslik': 'İstatistikler',
  'istatistikler.birim.adet': 'Adet',
  'istatistikler.birim.dakika': 'dakika',
  'istatistikler.birim.gun': 'gün',
  'istatistikler.birim.sise': 'şişe',
  'istatistikler.bos.yetki': 'Görüntüleyebileceğiniz istatistik bulunmuyor.',
  'istatistikler.fermantasyon.bos': 'Fermantasyon kaydı yok.',
  'istatistikler.fermantasyon.durumbaslik': 'Durum dağılımı',
  'istatistikler.fermantasyon.gunlukbrix': 'Günlük Brix düşüşü',
  'istatistikler.fermantasyon.ortalamasure': 'Ortalama süre',
  'istatistikler.fermantasyon.surearaligi': 'Süre aralığı',
  'istatistikler.fermantasyon.tamamlanan': 'Tamamlanan',
  'istatistikler.fici.bos': 'Fıçı kaydı yok.',
  'istatistikler.fici.buharlasma': 'Buharlaşma kaybı',
  'istatistikler.fici.buharlasmaipucu': 'Angel\'s share',
  'istatistikler.fici.doluluk': 'Doluluk',
  'istatistikler.fici.kapasite': 'Kapasite',
  'istatistikler.fici.kullanimaciklama': 'Kaçıncı dolum — kalite ve maliyet göstergesi',
  'istatistikler.fici.kullanimbaslik': 'Kullanım sayısı',
  'istatistikler.fici.kullanimbos': 'Kullanım verisi yok.',
  'istatistikler.fici.sayisi': 'Fıçı sayısı',
  'istatistikler.fici.yas': 'yaş',
  'istatistikler.fici.yasbaslik': 'Üretim yılına göre dağılım',
  'istatistikler.filtre.rekolteyili': 'Rekolte yılı',
  'istatistikler.filtre.tumyillar': 'Tüm yıllar',
  'istatistikler.fire.firesise': 'fire şişe',
  'istatistikler.fire.huniaciklama': 'Aşamalar arası hacim akışı',
  'istatistikler.fire.hunibaslik': 'Üzümden şişeye',
  'istatistikler.fire.kayipaciklama': 'En çok para kaybedilen aşama',
  'istatistikler.fire.kayipbaslik': 'Kayıp nerede oluşuyor?',
  'istatistikler.fire.sira': 'Şıra',
  'istatistikler.fire.siraverimi': 'Şıra verimi',
  'istatistikler.fire.siraverimiipucu': 'Sektör aralığı: 0,65–0,75',
  'istatistikler.fire.toplamkayip': 'Toplam kayıp',
  'istatistikler.fire.uzum': 'Üzüm',
  'istatistikler.hasat.alan': 'Alan (da)',
  'istatistikler.hasat.bag': 'Bağ',
  'istatistikler.hasat.bos': 'Hasat kaydı yok.',
  'istatistikler.hasat.cesit': 'Çeşit',
  'istatistikler.hasat.cesitaciklama': 'Ortalama Brix, hedef aralıkla karşılaştırmalı',
  'istatistikler.hasat.cesitbaslik': 'Çeşit bazında olgunluk',
  'istatistikler.hasat.cesitbos': 'Çeşit verisi yok.',
  'istatistikler.hasat.curuk': 'Çürük %',
  'istatistikler.hasat.durum': 'Durum',
  'istatistikler.hasat.hedef': 'Hedef',
  'istatistikler.hasat.hedefdisi': 'Hedef dışı',
  'istatistikler.hasat.hedefte': 'Hedefte',
  'istatistikler.hasat.kalitebaslik': 'Kalite sınıfı dağılımı',
  'istatistikler.hasat.kalitebos': 'Kalite verisi yok.',
  'istatistikler.hasat.kgasma': 'kg / asma',
  'istatistikler.hasat.kgdekar': 'kg / dekar',
  'istatistikler.hasat.ortbrix': 'Ort. Brix',
  'istatistikler.hasat.parsel': 'Parsel',
  'istatistikler.hasat.parselaciklama': 'Ham kilogram yanıltır; dekar başına verim karşılaştırılabilir ölçüdür',
  'istatistikler.hasat.parselbaslik': 'Parsel verimi',
  'istatistikler.hasat.parselbos': 'Parsel bazlı hasat kaydı yok.',
  'istatistikler.hasat.parselbosipucu': 'Üzüm kabulünde parsel seçilmemiş olabilir.',
  'istatistikler.hasat.uzumkg': 'Üzüm (kg)',
  'istatistikler.hasat.yilaciklama': 'Toplam üzüm ve ortalama Brix',
  'istatistikler.hasat.yilbaslik': 'Rekolte yılı karşılaştırması',
  'istatistikler.laboratuvar.analiz': 'Analiz',
  'istatistikler.laboratuvar.analizbirim': 'analiz',
  'istatistikler.laboratuvar.analizsayisi': 'Analiz sayısı',
  'istatistikler.laboratuvar.aylikbaslik': 'Aylık spesifikasyon dışı oranı',
  'istatistikler.laboratuvar.bos': 'Dönemde analiz yok.',
  'istatistikler.laboratuvar.enaz': 'En az',
  'istatistikler.laboratuvar.encok': 'En çok',
  'istatistikler.laboratuvar.olcum': 'Ölçüm',
  'istatistikler.laboratuvar.ortalama': 'Ortalama',
  'istatistikler.laboratuvar.ortonaysuresi': 'Ortalama onay süresi',
  'istatistikler.laboratuvar.parametre': 'Parametre',
  'istatistikler.laboratuvar.parametrebaslik': 'Parametre özetleri',
  'istatistikler.laboratuvar.parametrebos': 'Parametre ölçümü yok.',
  'istatistikler.laboratuvar.specdisi': 'Spesifikasyon dışı',
  'istatistikler.laboratuvar.specdisiyuzde': 'Spec dışı %',
  'istatistikler.sekme.bakim': 'Bakım',
  'istatistikler.sekme.fermantasyon': 'Fermantasyon',
  'istatistikler.sekme.fici': 'Fıçı',
  'istatistikler.sekme.fire': 'Kayıp Zinciri',
  'istatistikler.sekme.hasat': 'Bağ ve Hasat',
  'istatistikler.sekme.laboratuvar': 'Laboratuvar',
  'istatistikler.sekme.siseleme': 'Şişeleme',
  'istatistikler.sekme.stok': 'Stok',
  'istatistikler.siseleme.ambalajbaslik': 'Ambalaj kırılımı',
  'istatistikler.siseleme.ambalajbos': 'Ambalaj verisi yok.',
  'istatistikler.siseleme.aylikbaslik': 'Aylık üretim',
  'istatistikler.siseleme.bos': 'Tamamlanmış şişeleme emri yok.',
  'istatistikler.siseleme.fire': 'Fire',
  'istatistikler.siseleme.fireorani': 'Fire oranı',
  'istatistikler.siseleme.hat': 'Hat',
  'istatistikler.siseleme.hatbaslik': 'Hat karşılaştırması',
  'istatistikler.siseleme.hatbos': 'Hat verisi yok.',
  'istatistikler.siseleme.planlanan': 'Planlanan',
  'istatistikler.siseleme.sise': 'Şişe',
  'istatistikler.siseleme.uretilen': 'Üretilen',
  'istatistikler.siseleme.uretilensise': 'Üretilen şişe',
  'istatistikler.siseleme.verim': 'Verim',
  'istatistikler.stok.aktifkalem': 'Aktif kalem',
  'istatistikler.stok.bos': 'Dönemde stok hareketi yok.',
  'istatistikler.stok.donem': 'Dönem',
  'istatistikler.stok.donemcikisi': 'Dönem çıkışı',
  'istatistikler.stok.encokbaslik': 'En çok tüketilen kalemler',
  'istatistikler.stok.gunlukort': 'Günlük ort.',
  'istatistikler.stok.hareketsizaciklama': 'Dönem boyunca hiç çıkış olmayan kalemler — bağlı sermaye',
  'istatistikler.stok.hareketsizbaslik': 'Hareketsiz stok',
  'istatistikler.stok.hareketsizipucu': 'Dönemde hiç çıkış olmadı',
  'istatistikler.stok.hareketsizkalem': 'Hareketsiz kalem',
  'istatistikler.stok.hic': 'Hiç',
  'istatistikler.stok.kalem': 'Kalem',
  'istatistikler.stok.kategori': 'Kategori',
  'istatistikler.stok.sonhareket': 'Son hareket',
  'istatistikler.yukleniyor': 'İstatistikler hesaplanıyor…',
  'kullanicilar.aciklama': 'Rol tabanlı yetkilendirme · her rol yalnızca yetkili olduğu ekranları görür',
  'kullanicilar.baslik': 'Kullanıcılar ve Roller',
  'kullanicilar.bos.metin': 'Kullanıcı yok.',
  'kullanicilar.dugme.aktiflestir': 'Aktifleştir',
  'kullanicilar.dugme.ekle': 'Kullanıcı ekle',
  'kullanicilar.dugme.olustur': 'Oluştur',
  'kullanicilar.dugme.parolasifirla': 'Parola sıfırla',
  'kullanicilar.dugme.pasifeal': 'Pasife al',
  'kullanicilar.dugme.sifirla': 'Sıfırla',
  'kullanicilar.durum.aktif': 'Aktif',
  'kullanicilar.durum.pasif': 'Pasif',
  'kullanicilar.form.geciciparola': 'Geçici parola',
  'kullanicilar.form.parolaipucu': 'En az 10 karakter; büyük harf, küçük harf ve rakam içermeli. Kullanıcı ilk girişte değiştirir.',
  'kullanicilar.form.rolipucu': 'Birden fazla rol seçebilirsiniz (Ctrl ile)',
  'kullanicilar.form.yenigeciciparola': 'Yeni geçici parola',
  'kullanicilar.kart.rolaciklama': 'Bir role tıklayarak sahip olduğu yetkileri görebilirsiniz',
  'kullanicilar.kart.rolkatalog': 'Rol ve yetki kataloğu',
  'kullanicilar.parola.bilgi': 'Parola sıfırlandığında kullanıcının tüm oturumları kapatılır ve ilk girişte parola değiştirmesi istenir. İşlem denetim günlüğüne kaydedilir.',
  'kullanicilar.rol.yetkisayisi': 'yetki',
  'kullanicilar.tablo.adsoyad': 'Ad soyad',
  'kullanicilar.tablo.departman': 'Departman',
  'kullanicilar.tablo.durum': 'Durum',
  'kullanicilar.tablo.eposta': 'E-posta',
  'kullanicilar.tablo.islem': 'İşlem',
  'kullanicilar.tablo.kullaniciadi': 'Kullanıcı adı',
  'kullanicilar.tablo.roller': 'Roller',
  'kullanicilar.tablo.songiris': 'Son giriş',
  'laboratuvar.aciklama': 'Numune yönetimi, analiz sonuçları, spesifikasyonlar ve onay iş akışı',
  'laboratuvar.aitablo.deger': 'Değer',
  'laboratuvar.aitablo.ideal': 'İdeal',
  'laboratuvar.aitablo.parametre': 'Parametre',
  'laboratuvar.aitablo.puan': 'Puan',
  'laboratuvar.alan.alkol': 'Alkol (%vol)',
  'laboratuvar.alan.bulaniklik': 'Bulanıklık (NTU)',
  'laboratuvar.alan.kalintiseker': 'Kalıntı şeker (g/L)',
  'laboratuvar.alan.malikasit': 'Malik asit (g/L)',
  'laboratuvar.alan.not': 'Not',
  'laboratuvar.alan.numunetur': 'Numune türü',
  'laboratuvar.alan.parti': 'Parti',
  'laboratuvar.alan.ph': 'pH',
  'laboratuvar.alan.serbestso2': 'Serbest SO₂ (mg/L)',
  'laboratuvar.alan.toplamasitlik': 'Toplam asitlik (g/L)',
  'laboratuvar.alan.toplamso2': 'Toplam SO₂ (mg/L)',
  'laboratuvar.alan.ucucuasitlik': 'Uçucu asitlik (g/L)',
  'laboratuvar.alan.yogunluk': 'Yoğunluk',
  'laboratuvar.baslik': 'Laboratuvar',
  'laboratuvar.bos.numune': 'Numune kaydı yok.',
  'laboratuvar.bos.sonuc': 'Analiz sonucu yok.',
  'laboratuvar.bos.sonucipucu': 'Numune alıp sonuç girerek başlayın.',
  'laboratuvar.bos.spek': 'Spesifikasyon tanımlı değil.',
  'laboratuvar.bos.spekipucu': 'Spesifikasyonlar, analiz sonuçlarını otomatik denetlemek için kullanılır.',
  'laboratuvar.dugme.aiyorum': 'Yapay zekâ yorumu',
  'laboratuvar.dugme.numunal': 'Numune al',
  'laboratuvar.dugme.numunekaydet': 'Numuneyi kaydet ve sonuç gir',
  'laboratuvar.dugme.sonucgir': 'Sonuç gir',
  'laboratuvar.dugme.sonuckaydet': 'Sonucu kaydet',
  'laboratuvar.filtre.bekleyen': 'Onay bekleyenler',
  'laboratuvar.filtre.onay': 'Onay durumu',
  'laboratuvar.filtre.onaylanan': 'Onaylananlar',
  'laboratuvar.filtre.reddedilen': 'Reddedilenler',
  'laboratuvar.filtre.tumu': 'Tüm sonuçlar',
  'laboratuvar.kip.aiyorum': 'Yapay zekâ laboratuvar yorumu',
  'laboratuvar.kip.numune': 'Numune al',
  'laboratuvar.kip.sonuc': 'Analiz sonucu gir',
  'laboratuvar.numunetablo.alinma': 'Alınma',
  'laboratuvar.numunetablo.durum': 'Durum',
  'laboratuvar.numunetablo.kod': 'Kod',
  'laboratuvar.numunetablo.parti': 'Parti',
  'laboratuvar.numunetablo.sonuc': 'Sonuç',
  'laboratuvar.numunetablo.tank': 'Tank',
  'laboratuvar.numunetablo.tur': 'Tür',
  'laboratuvar.numunetur.kontrol': 'Kontrol',
  'laboratuvar.numunetur.rutin': 'Rutin',
  'laboratuvar.numunetur.sikayet': 'Şikâyet',
  'laboratuvar.numunetur.sislemeoncesi': 'Şişeleme öncesi',
  'laboratuvar.rozet.spekdisi': 'Spek. dışı',
  'laboratuvar.secim.seciniz': 'Seçiniz…',
  'laboratuvar.sekme.numune': 'Numuneler',
  'laboratuvar.sekme.sonuc': 'Analiz Sonuçları',
  'laboratuvar.sekme.spek': 'Spesifikasyonlar',
  'laboratuvar.spektablo.alan': 'Alan',
  'laboratuvar.spektablo.altsinir': 'Alt sınır',
  'laboratuvar.spektablo.birim': 'Birim',
  'laboratuvar.spektablo.parametre': 'Parametre',
  'laboratuvar.spektablo.saraptipi': 'Şarap tipi',
  'laboratuvar.spektablo.seviye': 'Seviye',
  'laboratuvar.spektablo.tumu': 'Tümü',
  'laboratuvar.spektablo.ustsinir': 'Üst sınır',
  'laboratuvar.tablo.alkol': 'Alkol',
  'laboratuvar.tablo.islem': 'İşlem',
  'laboratuvar.tablo.kod': 'Kod',
  'laboratuvar.tablo.onay': 'Onay',
  'laboratuvar.tablo.parti': 'Parti',
  'laboratuvar.tablo.ph': 'pH',
  'laboratuvar.tablo.seker': 'Şeker',
  'laboratuvar.tablo.serbestso2': 'Serb. SO₂',
  'laboratuvar.tablo.ta': 'TA',
  'laboratuvar.tablo.tarih': 'Tarih',
  'laboratuvar.tablo.toplamso2': 'Top. SO₂',
  'laboratuvar.tablo.ua': 'UA',
  'laboratuvar.uyari.redgerekce': 'Red gerekçesi (zorunlu):',
  'laboratuvar.yukleniyor.yorum': 'Analiz yorumlanıyor…',
  'pano.ai.aciklama': 'Yerel analiz · karar destek amaçlıdır',
  'pano.ai.baslik': 'Yapay zekâ önerileri',
  'pano.ai.bos': 'Risk göstergesi bulunamadı.',
  'pano.ai.bosipucu': 'Tüm partiler normal aralıkta.',
  'pano.asama.aciklama': 'Aktif partiler',
  'pano.asama.baslik': 'Parti aşama dağılımı',
  'pano.baslik': 'Kontrol Paneli',
  'pano.dusukstok.baslik': 'Minimum stok altındaki kalemler',
  'pano.dusukstok.bos': 'Kritik stok yok.',
  'pano.dusukstok.kalem': 'kalem',
  'pano.dusukstok.link': 'Stok',
  'pano.dusukstok.tablo.eksik': 'Eksik',
  'pano.dusukstok.tablo.kalem': 'Kalem',
  'pano.dusukstok.tablo.mevcut': 'Mevcut',
  'pano.dusukstok.tablo.minimum': 'Minimum',
  'pano.faaliyet.baslik': 'Son faaliyetler',
  'pano.faaliyet.bos': 'Henüz faaliyet yok.',
  'pano.faaliyet.sistem': 'sistem',
  'pano.fermantasyon.aktif': 'aktif fermantasyon',
  'pano.fermantasyon.baslik': 'Devam eden fermantasyonlar',
  'pano.fermantasyon.bos': 'Devam eden fermantasyon yok.',
  'pano.fermantasyon.gun': 'gün',
  'pano.fermantasyon.tahminibitis': 'Tahmini bitiş',
  'pano.fermantasyon.tankyok': 'tank yok',
  'pano.gorev.baslik': 'Yaklaşan işlemler',
  'pano.gorev.bos': 'Yaklaşan iş yok.',
  'pano.gorev.gecikti': 'Gecikti',
  'pano.gorev.gungecikti': 'gün gecikti',
  'pano.gorev.gunkaldi': 'gün kaldı',
  'pano.songuncelleme': 'Son güncelleme',
  'pano.stok.baslik': 'Stok değeri (kategori bazlı)',
  'pano.stok.seri': 'Değer (TRY)',
  'pano.tank.aktif': 'aktif tank',
  'pano.tank.baslik': 'Tank doluluk oranları',
  'pano.tank.bos': 'Tank kaydı yok.',
  'pano.tank.bosdurum': 'Boş',
  'pano.tank.yerlesim': 'Tank yerleşimi',
  'pano.tumu': 'Tümü',
  'pano.uretim.aciklama': 'Son 30 gün',
  'pano.uretim.baslik': 'Günlük üzüm kabulü (kg)',
  'pano.uretim.seri': 'Üzüm (kg)',
  'pano.uyari.acik': 'açık uyarı',
  'pano.uyari.baslik': 'Kritik uyarılar',
  'pano.uyari.bos': 'Açık uyarı yok.',
  'pano.uyari.bosipucu': 'Sistem normal çalışıyor.',
  'pano.yukleniyor': 'Kontrol paneli hazırlanıyor…',
  'partidetay.gecmis.baslik': 'İşlem geçmişi',
  'partidetay.gecmis.bos': 'Kayıt yok.',
  'partidetay.gerilink': 'Partiler',
  'partidetay.izleme.aciklama': 'Düğümleri sürükleyebilir, tekerlekle yakınlaştırabilirsiniz',
  'partidetay.izleme.baslik': 'İzlenebilirlik çizgesi',
  'partidetay.izleme.bos': 'Henüz bağlantı kaydı yok.',
  'partidetay.izleme.bosipucu': 'Transfer, kupaj veya şişeleme işlemi yapıldıkça çizge oluşur.',
  'partidetay.izleme.geri': 'Geriye (kaynağa)',
  'partidetay.izleme.ileri': 'İleriye (ürüne)',
  'partidetay.izleme.tam': 'Tam izleme',
  'partidetay.kupaj': 'kupaj',
  'partidetay.maliyet.aciklama': 'Varsayılan dolaylı gider oranlarıyla',
  'partidetay.maliyet.ambalaj': 'Ambalaj',
  'partidetay.maliyet.baslik': 'Maliyet dökümü',
  'partidetay.maliyet.enerji': 'Enerji',
  'partidetay.maliyet.fire': 'Fire',
  'partidetay.maliyet.genelgider': 'Genel gider',
  'partidetay.maliyet.iscilik': 'İşçilik',
  'partidetay.maliyet.katki': 'Katkı',
  'partidetay.maliyet.litrebasi': 'Litre başı',
  'partidetay.maliyet.toplam': 'Toplam maliyet',
  'partidetay.maliyet.uzum': 'Üzüm',
  'partidetay.maliyet.yetkiyok': 'Maliyet görüntüleme yetkiniz yok.',
  'partidetay.ozet.alkol': 'Alkol',
  'partidetay.ozet.asama': 'Aşama',
  'partidetay.ozet.durum': 'Durum',
  'partidetay.ozet.hacim': 'Hacim',
  'partidetay.ozet.ph': 'pH',
  'partidetay.ozet.tank': 'Tank',
  'partidetay.qrkodu': 'QR kodu',
  'partidetay.rekoltesi': 'rekoltesi',
  'partidetay.risk.aciklama': 'Yerel sayısal analiz · karar destek amaçlıdır',
  'partidetay.risk.baslik': 'Risk değerlendirmesi',
  'partidetay.tur.fici': 'Fıçı',
  'partidetay.tur.kabul': 'Üzüm kabulü',
  'partidetay.tur.parti': 'Parti',
  'partidetay.tur.siseleme': 'Şişeleme',
  'partidetay.tur.tank': 'Tank',
  'partiler.aciklama': 'Üzümden şişeye izlenebilir üretim partileri',
  'partiler.arama': 'Parti kodu veya adı ara…',
  'partiler.baslik': 'Partiler',
  'partiler.bos': 'Parti kaydı yok.',
  'partiler.bosipucu': 'Üzüm kabul kayıtlarından bir parti oluşturarak başlayın.',
  'partiler.dugme.olustur': 'Parti oluştur',
  'partiler.filtre.arialabel': 'Aşamaya göre filtrele',
  'partiler.filtre.tumasamalar': 'Tüm aşamalar',
  'partiler.form.ad': 'Parti adı',
  'partiler.form.adornek': 'Öküzgözü Rezerv 2026',
  'partiler.form.agirlikipucu': 'kg',
  'partiler.form.hacim': 'Başlangıç hacmi (L)',
  'partiler.form.hacimipucu': 'Şıra/must hacmi',
  'partiler.form.kabulsec': 'Kabul seçiniz…',
  'partiler.form.kaynakbaslik': 'Kaynak üzüm kabulleri',
  'partiler.form.kaynakekle': 'Kaynak ekle',
  'partiler.form.satirkaldir': 'Satırı kaldır',
  'partiler.form.siraipucu': 'şıra L',
  'partiler.form.tank': 'Tank',
  'partiler.form.tip': 'Şarap tipi',
  'partiler.hata.kaynakyok': 'En az bir üzüm kabul kaydı seçilmelidir.',
  'partiler.kip.baslik': 'Üzüm kabullerinden parti oluştur',
  'partiler.rozet.kupaj': 'Kupaj',
  'partiler.tablo.ad': 'Parti adı',
  'partiler.tablo.alkol': 'Alkol',
  'partiler.tablo.asama': 'Aşama',
  'partiler.tablo.cesit': 'Çeşit',
  'partiler.tablo.durum': 'Durum',
  'partiler.tablo.hacim': 'Hacim (L)',
  'partiler.tablo.kod': 'Kod',
  'partiler.tablo.rekolte': 'Rekolte',
  'partiler.tablo.tank': 'Tank',
  'partiler.tablo.tip': 'Tip',
  'partiler.tip.beyaz': 'Beyaz',
  'partiler.tip.kirmizi': 'Kırmızı',
  'partiler.tip.kopuklu': 'Köpüklü',
  'partiler.tip.rose': 'Roze',
  'partiler.tip.tatli': 'Tatlı',
  'raporlar.aciklama': 'Üretim performansı, maliyet analizi ve dışa aktarma',
  'raporlar.baslik': 'Raporlar',
  'raporlar.birim.sise': 'şişe',
  'raporlar.disaaktar.aciklama': 'Excel, CSV ve PDF biçimlerinde indirin · her indirme denetim günlüğüne yazılır',
  'raporlar.disaaktar.baslik': 'Dışa aktarma',
  'raporlar.disaaktar.yetkiyok': 'Dışa aktarma yetkiniz yok.',
  'raporlar.grafik.aylik': 'Aylık üzüm kabulü',
  'raporlar.grafik.cesit': 'Çeşit bazlı üzüm kabulü',
  'raporlar.maliyet.ad': 'Ad',
  'raporlar.maliyet.baslik': 'Parti bazlı maliyet özeti',
  'raporlar.maliyet.bos': 'Maliyet hesaplanacak parti yok.',
  'raporlar.maliyet.fire': 'Fire',
  'raporlar.maliyet.hacim': 'Hacim (L)',
  'raporlar.maliyet.parti': 'Parti',
  'raporlar.maliyet.rekolte': 'Rekolte',
  'raporlar.maliyet.sise': 'Şişe',
  'raporlar.maliyet.toplammaliyet': 'Toplam maliyet',
  'raporlar.maliyet.tryl': 'TRY/L',
  'raporlar.maliyet.trysise': 'TRY/şişe',
  'raporlar.ozet.aktifparti': 'Aktif parti',
  'raporlar.ozet.kabulsayisi': 'Kabul sayısı',
  'raporlar.ozet.siselenen': 'Şişelenen',
  'raporlar.ozet.uzumkabulu': 'Üzüm kabulü',
  'raporlar.ozet.verim': 'Verim',
  'raporlar.rapor.fermantasyon.aciklama': 'Başlangıç/bitiş, maya, ölçüm sayısı',
  'raporlar.rapor.fermantasyon.ad': 'Fermantasyon',
  'raporlar.rapor.laboratuvar.aciklama': 'Tüm parametreler ve onay durumu',
  'raporlar.rapor.laboratuvar.ad': 'Laboratuvar analizleri',
  'raporlar.rapor.maliyet.aciklama': 'Üzüm, katkı, ambalaj ve dolaylı giderler',
  'raporlar.rapor.maliyet.ad': 'Parti bazlı maliyet',
  'raporlar.rapor.stok.aciklama': 'Mevcut miktar, minimum stok, değer',
  'raporlar.rapor.stok.ad': 'Stok durumu',
  'raporlar.rapor.uretim.aciklama': 'Kantar kayıtları, kalite ve tutarlar',
  'raporlar.rapor.uretim.ad': 'Üzüm kabul / üretim',
  'recete.aciklama': 'Ürün reçeteleri, kupaj senaryoları ve yetkili onayı',
  'recete.alan.hacim': 'Hacim (L)',
  'recete.alan.hedeftank': 'Hedef tank',
  'recete.alan.senaryoadi': 'Senaryo adı',
  'recete.alan.sonucparti': 'Sonuç parti adı',
  'recete.baslik': 'Reçete ve Kupaj',
  'recete.bilesen.baslik': 'Bileşen partiler (en az 2)',
  'recete.birim.gun': 'gün',
  'recete.bos.kupaj': 'Kupaj senaryosu yok.',
  'recete.bos.kupajipucu': 'En az iki partiden yeni bir kupaj senaryosu oluşturun; sistem alkol, pH ve maliyeti önceden hesaplar.',
  'recete.bos.recete': 'Reçete yok.',
  'recete.dugme.bilesenekle': 'Bileşen ekle',
  'recete.dugme.senaryo': 'Kupaj senaryosu',
  'recete.dugme.senaryoolustur': 'Senaryoyu oluştur',
  'recete.dugme.uygula': 'Kupajı uygula',
  'recete.dugme.uygulaonay': 'Uygula',
  'recete.hata.enazikibilesen': 'Kupaj en az iki bileşen içermelidir.',
  'recete.kart.bilesen': 'bileşen',
  'recete.kart.hedef': 'hedef',
  'recete.kart.uygulandi': 'Uygulandı',
  'recete.kip.olustur': 'Kupaj senaryosu oluştur',
  'recete.kip.uygula': 'Kupajı uygula',
  'recete.not.tahmin': 'Tahminler hacim ağırlıklıdır; pH, H⁺ derişimi üzerinden hesaplanır.',
  'recete.olcut.alkol': 'Alkol',
  'recete.olcut.maliyet': 'Maliyet',
  'recete.olcut.ph': 'pH',
  'recete.olcut.ta': 'TA',
  'recete.recetetablo.bilesen': 'Bileşen',
  'recete.recetetablo.maliyet': 'Maliyet',
  'recete.recetetablo.oranmiktar': 'Oran/Miktar',
  'recete.recetetablo.tur': 'Tür',
  'recete.secim.bos': 'boş',
  'recete.secim.partiseciniz': 'Parti seçiniz…',
  'recete.sekme.kupaj': 'Kupaj Senaryoları',
  'recete.sekme.recete': 'Reçeteler',
  'recete.tablo.hacim': 'Hacim (L)',
  'recete.tablo.kaynakparti': 'Kaynak parti',
  'recete.tablo.oran': 'Oran',
  'recete.uygula.not': 'Uygulama sonucunda yeni bir parti oluşturulur; kaynak partilerin hacmi düşer ve izlenebilirlik bağlantıları otomatik kurulur. Bu işlem geri alınamaz.',
  'recete.varsayilan.kupajeki': 'kupaj',
  'saraptipi.beyaz': 'Beyaz',
  'saraptipi.kirmizi': 'Kırmızı',
  'saraptipi.kopuklu': 'Köpüklü',
  'saraptipi.rose': 'Roze',
  'saraptipi.tatli': 'Tatlı',
  'siseleme.aciklama': 'Şişeleme emirleri, hat takibi, LOT numarası ve etiket önizleme',
  'siseleme.alan.barkod': 'Barkod',
  'siseleme.alan.fire': 'Fire (L)',
  'siseleme.alan.hatkodu': 'Hat kodu',
  'siseleme.alan.hedefdepo': 'Hedef depo',
  'siseleme.alan.kalitenotu': 'Kalite notu',
  'siseleme.alan.koliadedi': 'Koli adedi',
  'siseleme.alan.parti': 'Parti',
  'siseleme.alan.planlanansise': 'Planlanan şişe',
  'siseleme.alan.rededilen': 'Red edilen',
  'siseleme.alan.sisehacmi': 'Şişe hacmi (ml)',
  'siseleme.alan.uretilensise': 'Üretilen şişe',
  'siseleme.alan.urunadi': 'Ürün adı',
  'siseleme.ambalaj.baslik': 'Ambalaj bileşenleri (stoktan düşülecektir)',
  'siseleme.ambalaj.etiket': 'Etiket',
  'siseleme.ambalaj.kapsul': 'Kapsül',
  'siseleme.ambalaj.koli': 'Koli',
  'siseleme.ambalaj.mantar': 'Mantar / kapak',
  'siseleme.ambalaj.sise': 'Şişe',
  'siseleme.baslik': 'Şişeleme ve Paketleme',
  'siseleme.bitir.not': 'Bitirme işlemi ambalaj stoğunu düşer, bitmiş ürünü depoya alır ve parti hacmini günceller.',
  'siseleme.bos.ipucu': 'Şişelemeye hazır bir parti seçerek emir oluşturun.',
  'siseleme.bos.kayit': 'Şişeleme emri yok.',
  'siseleme.dugme.bitir': 'Şişelemeyi bitir',
  'siseleme.dugme.emir': 'Şişeleme emri',
  'siseleme.dugme.emirolustur': 'Emri oluştur',
  'siseleme.dugme.etiket': 'Etiket önizleme',
  'siseleme.dugme.hatbaslat': 'Hattı başlat',
  'siseleme.dugme.qr': 'QR kodu',
  'siseleme.dugme.tamamla': 'Şişelemeyi tamamla',
  'siseleme.etiket.uyari': 'Bu önizleme yasal etiket gerekliliklerinin tamamını içermez; basımdan önce mevzuata göre kontrol edilmelidir.',
  'siseleme.kip.bitir': 'Şişelemeyi bitir',
  'siseleme.kip.emir': 'Şişeleme emri oluştur',
  'siseleme.kip.etiket': 'Etiket önizleme',
  'siseleme.onay.kalitekontrol': 'Kalite kontrolünden geçti',
  'siseleme.secim.seciniz': 'Seçiniz…',
  'siseleme.secim.varsayilandepo': 'Varsayılan depo',
  'siseleme.tablo.durum': 'Durum',
  'siseleme.tablo.emir': 'Emir',
  'siseleme.tablo.fire': 'Fire',
  'siseleme.tablo.hat': 'Hat',
  'siseleme.tablo.islem': 'İşlem',
  'siseleme.tablo.lotno': 'LOT no',
  'siseleme.tablo.parti': 'Parti',
  'siseleme.tablo.planlanan': 'Planlanan',
  'siseleme.tablo.uretilen': 'Üretilen',
  'siseleme.tablo.urun': 'Ürün',
  'siseleme.tablo.verim': 'Verim',
  'stok.aciklama': 'Hammadde, ambalaj ve bitmiş ürün stoğu · FIFO/FEFO destekli',
  'stok.baslik': 'Stok ve Sevkiyat',
  'stok.dugme.cikis': 'Çıkış',
  'stok.dugme.giris': 'Giriş',
  'stok.dugme.sayim': 'Sayım',
  'stok.dugme.transfer': 'Transfer',
  'stok.filtre.kategori': 'Kategori',
  'stok.form.birimmaliyet': 'Birim maliyet (TRY)',
  'stok.form.depo': 'Depo',
  'stok.form.hedefdepo': 'Hedef depo',
  'stok.form.kalem': 'Stok kalemi',
  'stok.form.kaynakdepo': 'Kaynak depo',
  'stok.form.miktar': 'Miktar',
  'stok.form.not': 'Not',
  'stok.form.particodu': 'Parti kodu',
  'stok.form.particoduipucu': 'Boş bırakılırsa otomatik üretilir',
  'stok.form.sayilanmiktar': 'Sayılan miktar',
  'stok.form.seciniz': 'Seçiniz…',
  'stok.form.skt': 'Son kullanma tarihi',
  'stok.hareket.birimmaliyet': 'Birim maliyet',
  'stok.hareket.depo': 'Depo',
  'stok.hareket.kalem': 'Kalem',
  'stok.hareket.kullanici': 'Kullanıcı',
  'stok.hareket.miktar': 'Miktar',
  'stok.hareket.tarih': 'Tarih',
  'stok.hareket.tur': 'Tür',
  'stok.hareket.tutar': 'Tutar',
  'stok.kategori.ambalaj': 'Ambalaj',
  'stok.kategori.bitmisurun': 'Bitmiş ürün',
  'stok.kategori.hammadde': 'Hammadde',
  'stok.kategori.katki': 'Katkı',
  'stok.kategori.sarf': 'Sarf malzemesi',
  'stok.kategori.tumu': 'Tüm kategoriler',
  'stok.kategori.yedekparca': 'Yedek parça',
  'stok.kip.cikis': 'Stok çıkışı (FIFO/FEFO)',
  'stok.kip.giris': 'Stok girişi',
  'stok.kip.sayim': 'Sayım düzeltmesi',
  'stok.kip.transfer': 'Depolar arası transfer',
  'stok.satinalma.aratoplam': 'Ara toplam',
  'stok.satinalma.bos': 'Satın alma siparişi yok.',
  'stok.satinalma.durum': 'Durum',
  'stok.satinalma.geneltoplam': 'Genel toplam',
  'stok.satinalma.kalem': 'Kalem',
  'stok.satinalma.siparistarihi': 'Sipariş tarihi',
  'stok.satinalma.tedarikci': 'Tedarikçi',
  'stok.sekme.hareket': 'Hareketler',
  'stok.sekme.satinalma': 'Satın Alma',
  'stok.sekme.seviye': 'Stok Seviyeleri',
  'stok.sekme.sevkiyat': 'Sevkiyat',
  'stok.seviye.bos': 'Stok kartı yok.',
  'stok.seviye.deger': 'Değer',
  'stok.seviye.depolar': 'Depolar',
  'stok.seviye.kalem': 'Kalem',
  'stok.seviye.kategori': 'Kategori',
  'stok.seviye.mevcut': 'Mevcut',
  'stok.seviye.min': 'Min.',
  'stok.seviye.skt': 'SKT',
  'stok.sevkiyat.bos': 'Sevkiyat kaydı yok.',
  'stok.sevkiyat.durum': 'Durum',
  'stok.sevkiyat.musteri': 'Müşteri',
  'stok.sevkiyat.siparis': 'Sipariş',
  'stok.sevkiyat.tasiyici': 'Taşıyıcı',
  'stok.sevkiyat.tutar': 'Tutar',
  'stok.tablo.kod': 'Kod',
  'tablo.sayfalama.kayit': 'kayıt',
  'tablo.sayfalama.onceki': 'Önceki sayfa',
  'tablo.sayfalama.sayfa': 'sayfa',
  'tablo.sayfalama.sonraki': 'Sonraki sayfa',
  'tanklar.baslik': 'Tanklar',
  'tanklar.bolge.tank': 'tank',
  'tanklar.bos': 'Tank kaydı yok.',
  'tanklar.dugme.kaydet': 'Transferi kaydet',
  'tanklar.dugme.transfer': 'Transfer',
  'tanklar.form.fire': 'Fire (L)',
  'tanklar.form.hacim': 'Hacim (L)',
  'tanklar.form.hedefipucu': 'Boşaltımda boş bırakın',
  'tanklar.form.hedeftank': 'Hedef tank',
  'tanklar.form.islemturu': 'İşlem türü',
  'tanklar.form.kaynakipucu': 'Dolumda boş bırakın',
  'tanklar.form.kaynaktank': 'Kaynak tank',
  'tanklar.form.lbos': 'L boş',
  'tanklar.form.ldolu': 'L dolu',
  'tanklar.form.not': 'Not',
  'tanklar.form.parti': 'Parti',
  'tanklar.form.seciniz': 'Seçiniz…',
  'tanklar.gorunum.liste': 'Liste',
  'tanklar.gorunum.yerlesim': 'Yerleşim',
  'tanklar.ipucu.baslik': 'İpucu',
  'tanklar.ipucu.metin': 'Transfer sırasında sistem kaynak tankta yeterli hacim, hedef tankta yeterli boş kapasite ve temizlik durumunu otomatik denetler. Kirli bir tanka dolum yapılamaz; önce temizlik kaydı girilmelidir.',
  'tanklar.islem.aktarma': 'Aktarma (racking)',
  'tanklar.islem.bosaltim': 'Boşaltım',
  'tanklar.islem.dolum': 'Dolum (tanka al)',
  'tanklar.islem.tankarasi': 'Tanklar arası transfer',
  'tanklar.kip.baslik': 'Tank transferi',
  'tanklar.ozet.doluluk': 'doluluk',
  'tanklar.ozet.toplam': 'Toplam',
  'tanklar.tablo.bolge': 'Bölge',
  'tanklar.tablo.dolu': 'Dolu (L)',
  'tanklar.tablo.doluluk': 'Doluluk',
  'tanklar.tablo.durum': 'Durum',
  'tanklar.tablo.kapasite': 'Kapasite (L)',
  'tanklar.tablo.kod': 'Kod',
  'tanklar.tablo.parti': 'Parti',
  'tanklar.tablo.sontemizlik': 'Son temizlik',
  'tanklar.tablo.temizlik': 'Temizlik',
  'tanklar.tablo.tip': 'Tip',
  'tanklar.tank.dolu': 'dolu',
  'yapayzeka.aciklama': 'Yerel model (LM Studio), Claude ve NVIDIA sağlayıcıları tek arayüzde',
  'yapayzeka.alan.gorev': 'Görev türü',
  'yapayzeka.alan.model': 'Model',
  'yapayzeka.alan.partiler': 'Partiler',
  'yapayzeka.alan.saglayici': 'Sağlayıcı',
  'yapayzeka.analiz.bakim_tahmin': 'Bakım zamanı tahmini',
  'yapayzeka.analiz.rapor': 'Doğal dil raporu',
  'yapayzeka.analiz.stok_tahmin': 'Stok tükenme tahmini',
  'yapayzeka.baglam.panoekle': 'İşletme genel durumunu ekle',
  'yapayzeka.baglam.rag': 'Doküman araması (RAG) kullan',
  'yapayzeka.baslik': 'Yapay Zekâ Çalışma Merkezi',
  'yapayzeka.bos.ipucu': 'Aşağıdan bir soru yazarak başlayın. Sağlayıcı kapalıysa sistem sizi bilgilendirir; uygulama çalışmaya devam eder.',
  'yapayzeka.bos.metin': 'Henüz konuşma seçilmedi.',
  'yapayzeka.dugme.gonder': 'Gönder',
  'yapayzeka.gizlilik.harici': 'Harici bulut sağlayıcı. Şaraphane verisi gönderilmeden önce kapsam onayınız istenir.',
  'yapayzeka.gizlilik.yerel': 'Yerel model — veriler bilgisayardan çıkmaz.',
  'yapayzeka.gorev.dokumantasyon': 'Dokümantasyon yazarı',
  'yapayzeka.gorev.genel': 'Genel',
  'yapayzeka.gorev.hata_teshis': 'Hata teşhis uzmanı',
  'yapayzeka.gorev.kalite_kontrol': 'Kalite kontrol yardımcısı',
  'yapayzeka.gorev.kod_gelistirici': 'Kod geliştirici',
  'yapayzeka.gorev.rapor_yazari': 'Rapor yazarı',
  'yapayzeka.gorev.saraphane_danismani': 'Şaraphane danışmanı',
  'yapayzeka.gorev.veri_analisti': 'Veri analisti',
  'yapayzeka.kapsam.ad': 'Ad',
  'yapayzeka.kapsam.alanlar': 'Gönderilecek alanlar',
  'yapayzeka.kapsam.baslik': 'Gönderilecek veri kapsamı',
  'yapayzeka.kapsam.karakter': 'karakter gönderilecek. Hassas veriler için yerel modeli (LM Studio) tercih edebilirsiniz.',
  'yapayzeka.kapsam.kod': 'Kod',
  'yapayzeka.kapsam.onayla': 'Onaylıyorum, gönder',
  'yapayzeka.kapsam.tur': 'Tür',
  'yapayzeka.kapsam.yaklasik': 'Yaklaşık',
  'yapayzeka.kart.analiz': 'Hazır analizler',
  'yapayzeka.kart.baglam': 'Veri bağlamı',
  'yapayzeka.kart.baglamaciklama': 'Modele verilecek şaraphane kayıtları',
  'yapayzeka.kart.kullanim': 'Kullanım (30 gün)',
  'yapayzeka.kart.saglayici': 'Sağlayıcı ve görev',
  'yapayzeka.kart.sohbet': 'Sohbet',
  'yapayzeka.kullanim.cikis': 'çıkış',
  'yapayzeka.kullanim.giris': 'giriş',
  'yapayzeka.kullanim.hataadet': 'hata',
  'yapayzeka.kullanim.istek': 'Toplam istek:',
  'yapayzeka.kullanim.istekadet': 'istek',
  'yapayzeka.kullanim.maliyet': 'Tahmini maliyet:',
  'yapayzeka.kullanim.token': 'Token:',
  'yapayzeka.model.varsayilan': 'Varsayılan',
  'yapayzeka.saglayici.kapali': 'kapalı',
  'yapayzeka.saglayici.otomatik': 'Otomatik (göreve göre)',
  'yapayzeka.sohbet.konusmano': 'Konuşma',
  'yapayzeka.sohbet.saniye': 'sn',
  'yapayzeka.sohbet.token': 'token',
  'yapayzeka.sohbet.yanitliyor': 'Model yanıtlıyor…',
  'yapayzeka.sohbet.yenigorev': 'Yeni bir görev başlatın — yanıtlar karar destek amaçlıdır',
  'yapayzeka.sohbet.yenikonusma': 'Yeni konuşma',
  'yapayzeka.sohbet.yertutucu': 'Örn: PRT-2025-0002 partisinde uçucu asitlik yükseliyor, ne yapmalıyım?',
  'yapayzeka.uyari.oncesi': 'Yapay zekâ çıktıları',
  'yapayzeka.uyari.sonrasi': 'niteliğindedir. Kritik üretim değerleri yapay zekâ tarafından değiştirilemez; her değişiklik yetkili kullanıcı onayı gerektirir.',
  'yapayzeka.uyari.vurgu': 'karar destek',
  'yedekleme.aciklama': 'Veritabanının tutarlı kopyası · WAL kipinde bile eksiksiz',
  'yedekleme.baslik': 'Yedekleme',
  'yedekleme.bilgi.kopya1': 'Yedek dosyası',
  'yedekleme.bilgi.kopya2': ': parola özetleri, şifreli API anahtarları ve denetim günlüğü içerir. Bu nedenle indirme ayrı bir yetkiye bağlıdır ve her indirme denetim günlüğüne kaydedilir.',
  'yedekleme.bilgi.kopyavurgu': 'tüm veritabanının kopyasıdır',
  'yedekleme.bilgi.ortam1': 'Yedekleri düzenli olarak',
  'yedekleme.bilgi.ortam2': 'kopyalayın; aynı diskteki yedek, disk arızasında birlikte kaybolur.',
  'yedekleme.bilgi.ortamvurgu': 'farklı bir fiziksel ortama',
  'yedekleme.bos.ipucu': 'Üretim verisi girmeye başlamadan önce ilk yedeği alın.',
  'yedekleme.bos.metin': 'Henüz yedek alınmamış.',
  'yedekleme.disk.azaliyor': 'Disk alanı azalıyor',
  'yedekleme.disk.bosalan': 'Boş disk alanı',
  'yedekleme.disk.boyut': 'Yedeklerin boyutu',
  'yedekleme.disk.konum': 'Konum',
  'yedekleme.disk.sayi': 'Yedek sayısı',
  'yedekleme.dugme.al': 'Yedek al',
  'yedekleme.dugme.aliniyor': 'Yedek alınıyor…',
  'yedekleme.dugme.indir': 'İndir',
  'yedekleme.dugme.temizle': 'Eskileri temizle',
  'yedekleme.dugme.temizleipucu': 'Saklama politikasına göre eskileri sil',
  'yedekleme.kart.liste': 'Yedekler',
  'yedekleme.kart.siralama': 'En yeniden eskiye',
  'yedekleme.kip.silbaslik': 'Yedeği sil',
  'yedekleme.kip.silmetin': 'kalıcı olarak silinecek. Bu işlem geri alınamaz.',
  'yedekleme.secenek.belgeler': 'Belgeleri de arşivle',
  'yedekleme.tablo.boyut': 'Boyut',
  'yedekleme.tablo.dosya': 'Dosya',
  'yedekleme.tablo.islem': 'İşlem',
  'yedekleme.tablo.olusturma': 'Oluşturma',
  'yedekleme.tablo.tur': 'Tür',
  'yedekleme.tur.belgeler': 'Belgeler',
  'yedekleme.tur.veritabani': 'Veritabanı',
  'yedekleme.uyari.yetkiyok': 'Yedek dosyasını indirme yetkiniz yok. Yedekler sunucuda saklanır; indirme yetkisi sistem yöneticisindedir.',
  'grup.genel': 'Genel',
  'grup.uretim': 'Üretim',
  'grup.kalite': 'Kalite',
  'grup.lojistik': 'Lojistik',
  'grup.analiz': 'Analiz',
  'grup.ai': 'Yapay Zekâ',
  'grup.sistem': 'Sistem',
  'kpi.aktif_parti': 'Aktif parti',
  'kpi.toplam_hacim': 'Toplam şarap hacmi',
  'kpi.fermantasyon': 'Devam eden fermantasyon',
  'kpi.tank_doluluk': 'Tank doluluk oranı',
  'kpi.uzum_kabul': 'Son 30 gün üzüm kabulü',
  'kpi.sise': 'Toplam şişelenen',
  'kpi.uyari': 'Açık uyarı',
  'kpi.lab_onay': 'Onay bekleyen analiz',
}
