"""egitim ilerleme tablosu

Revision ID: 560ad4aebe38
Revises: 0001
Create Date: 2026-08-15 13:00:43.218534
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '560ad4aebe38'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_code', sa.String(length=64), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_training_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_progress')),
    sa.UniqueConstraint('user_id', 'module_code', name='uq_training_user_module')
    )
    with op.batch_alter_table('training_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_progress_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_progress_module_code'), ['module_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_training_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_training_user')
        batch_op.drop_index(batch_op.f('ix_training_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_progress_module_code'))
        batch_op.drop_index(batch_op.f('ix_training_progress_created_at'))

    op.drop_table('training_progress')
    # ### end Alembic commands ###
